// ---------------------------------------------------------------------------
// KT Markets — page content.
// Prices are illustrative sample data for the product page, not a live feed.
// ---------------------------------------------------------------------------

/**
 * Deterministic pseudo-random price series for the inline sparklines. Using a
 * seeded generator keeps the charts identical on every render (and between
 * server and client) while still looking like real intraday movement.
 */
function makeSeries(seed, drift) {
  let state = seed
  let value = 100
  return Array.from({ length: 24 }, () => {
    state = (state * 1103515245 + 12345) % 2147483648
    const noise = (state / 2147483648 - 0.5) * 3.2
    value = Math.max(value + drift + noise, 1)
    return Number(value.toFixed(2))
  })
}

export const marketCategories = ['All', 'Crypto', 'Stocks', 'Indices', 'Forex', 'Commodities']

export const marketAssets = [
  // ------------------------------------------------------------------ CRYPTO
  {
    symbol: 'BTC',
    pair: 'BTC/USD',
    name: 'Bitcoin',
    category: 'Crypto',
    price: 67420.5,
    change: 4.25,
    prefix: '$',
    decimals: 2,
    marketCap: '$1.33T',
    volume: '$42.1B',
    high: 68120.0,
    low: 64880.4,
    about:
      'The original proof-of-work blockchain and the largest digital asset by market capitalisation. Supply is capped at 21 million coins.',
    series: makeSeries(11, 0.42),
  },
  {
    symbol: 'ETH',
    pair: 'ETH/USD',
    name: 'Ethereum',
    category: 'Crypto',
    price: 3580.12,
    change: 2.8,
    prefix: '$',
    decimals: 2,
    marketCap: '$430.2B',
    volume: '$18.6B',
    high: 3612.9,
    low: 3468.15,
    about: 'A programmable settlement layer for smart contracts, rollups and the majority of on-chain applications.',
    series: makeSeries(23, 0.3),
  },
  {
    symbol: 'SOL',
    pair: 'SOL/USD',
    name: 'Solana',
    category: 'Crypto',
    price: 184.6,
    change: 8.15,
    prefix: '$',
    decimals: 2,
    marketCap: '$85.4B',
    volume: '$4.9B',
    high: 188.2,
    low: 168.75,
    about: 'A high-throughput chain optimised for low-cost transactions and consumer-facing payment applications.',
    series: makeSeries(31, 0.75),
  },
  {
    symbol: 'BNB',
    pair: 'BNB/USD',
    name: 'BNB',
    category: 'Crypto',
    price: 580.4,
    change: -1.1,
    prefix: '$',
    decimals: 2,
    marketCap: '$84.9B',
    volume: '$1.6B',
    high: 592.3,
    low: 576.1,
    about: 'The native asset of the BNB Chain ecosystem, used for transaction fees and network governance.',
    series: makeSeries(43, -0.12),
  },
  {
    symbol: 'XRP',
    pair: 'XRP/USD',
    name: 'Ripple',
    category: 'Crypto',
    price: 0.62,
    change: 3.4,
    prefix: '$',
    decimals: 4,
    marketCap: '$34.6B',
    volume: '$1.2B',
    high: 0.639,
    low: 0.598,
    about: 'A payment-focused ledger built for cross-border settlement between financial institutions.',
    series: makeSeries(57, 0.34),
  },
  {
    symbol: 'ADA',
    pair: 'ADA/USD',
    name: 'Cardano',
    category: 'Crypto',
    price: 0.48,
    change: -0.85,
    prefix: '$',
    decimals: 4,
    marketCap: '$17.1B',
    volume: '$412M',
    high: 0.492,
    low: 0.474,
    about: 'A research-driven proof-of-stake network with a formal-methods approach to protocol upgrades.',
    series: makeSeries(67, -0.1),
  },
  {
    symbol: 'DOGE',
    pair: 'DOGE/USD',
    name: 'Dogecoin',
    category: 'Crypto',
    price: 0.148,
    change: 5.6,
    prefix: '$',
    decimals: 4,
    marketCap: '$21.4B',
    volume: '$988M',
    high: 0.152,
    low: 0.139,
    about: 'A community-driven payment coin with unlimited supply and consistently high retail trading volume.',
    series: makeSeries(73, 0.55),
  },
  {
    symbol: 'AVAX',
    pair: 'AVAX/USD',
    name: 'Avalanche',
    category: 'Crypto',
    price: 34.82,
    change: -2.35,
    prefix: '$',
    decimals: 2,
    marketCap: '$13.8B',
    volume: '$486M',
    high: 36.1,
    low: 34.2,
    about: 'A multi-chain platform whose subnet architecture lets teams launch application-specific networks.',
    series: makeSeries(83, -0.24),
  },
  {
    symbol: 'MATIC',
    pair: 'MATIC/USD',
    name: 'Polygon',
    category: 'Crypto',
    price: 0.72,
    change: 1.95,
    prefix: '$',
    decimals: 4,
    marketCap: '$7.1B',
    volume: '$318M',
    high: 0.735,
    low: 0.703,
    about: 'A scaling ecosystem for Ethereum combining zk-rollups with a proof-of-stake sidechain.',
    series: makeSeries(97, 0.2),
  },
  {
    symbol: 'LINK',
    pair: 'LINK/USD',
    name: 'Chainlink',
    category: 'Crypto',
    price: 16.4,
    change: 3.05,
    prefix: '$',
    decimals: 2,
    marketCap: '$9.6B',
    volume: '$402M',
    high: 16.85,
    low: 15.82,
    about: 'A decentralised oracle network that feeds off-chain market data into smart contracts.',
    series: makeSeries(101, 0.31),
  },

  // ------------------------------------------------------------------ STOCKS
  {
    symbol: 'AAPL',
    pair: 'NASDAQ',
    name: 'Apple Inc.',
    category: 'Stocks',
    price: 224.3,
    change: -0.45,
    prefix: '$',
    decimals: 2,
    marketCap: '$3.44T',
    volume: '48.2M',
    high: 226.4,
    low: 223.1,
    about: 'Consumer hardware, services and silicon. The services segment now drives most of the margin expansion.',
    series: makeSeries(113, -0.05),
  },
  {
    symbol: 'NVDA',
    pair: 'NASDAQ',
    name: 'NVIDIA Corp.',
    category: 'Stocks',
    price: 128.9,
    change: 5.12,
    prefix: '$',
    decimals: 2,
    marketCap: '$3.17T',
    volume: '312.6M',
    high: 130.2,
    low: 121.4,
    about: 'Accelerated computing and data-centre GPUs, with the networking stack an increasing share of revenue.',
    series: makeSeries(127, 0.52),
  },
  {
    symbol: 'MSFT',
    pair: 'NASDAQ',
    name: 'Microsoft Corp.',
    category: 'Stocks',
    price: 448.2,
    change: 1.45,
    prefix: '$',
    decimals: 2,
    marketCap: '$3.33T',
    volume: '18.4M',
    high: 450.1,
    low: 442.6,
    about: 'Cloud infrastructure, productivity software and enterprise AI tooling under one licensing umbrella.',
    series: makeSeries(139, 0.16),
  },
  {
    symbol: 'GOOGL',
    pair: 'NASDAQ',
    name: 'Alphabet Inc.',
    category: 'Stocks',
    price: 178.6,
    change: 0.95,
    prefix: '$',
    decimals: 2,
    marketCap: '$2.19T',
    volume: '22.1M',
    high: 179.9,
    low: 176.8,
    about: 'Search advertising plus cloud, with capital expenditure increasingly weighted to AI infrastructure.',
    series: makeSeries(149, 0.11),
  },
  {
    symbol: 'AMZN',
    pair: 'NASDAQ',
    name: 'Amazon.com Inc.',
    category: 'Stocks',
    price: 186.4,
    change: 2.1,
    prefix: '$',
    decimals: 2,
    marketCap: '$1.94T',
    volume: '38.7M',
    high: 187.8,
    low: 182.4,
    about: 'Retail marketplace and logistics, with AWS contributing the majority of consolidated operating income.',
    series: makeSeries(157, 0.22),
  },
  {
    symbol: 'TSLA',
    pair: 'NASDAQ',
    name: 'Tesla Inc.',
    category: 'Stocks',
    price: 210.8,
    change: -3.2,
    prefix: '$',
    decimals: 2,
    marketCap: '$672B',
    volume: '96.3M',
    high: 218.4,
    low: 209.1,
    about: 'Electric vehicles, energy storage and autonomy software, with margins tightly coupled to delivery volume.',
    series: makeSeries(167, -0.34),
  },
  {
    symbol: 'NFLX',
    pair: 'NASDAQ',
    name: 'Netflix',
    category: 'Stocks',
    price: 498.5,
    change: 3.8,
    prefix: '$',
    decimals: 2,
    marketCap: '$1.26T',
    volume: '14.9M',
    high: 501.2,
    low: 480.6,
    about: 'Social advertising at global scale, funding a long-horizon bet on reality labs and open-weight models.',
    series: makeSeries(179, 0.39),
  },
  {
    symbol: 'RELIANCE',
    pair: 'NSE',
    name: 'Reliance Industries',
    category: 'Stocks',
    price: 2984.5,
    change: 1.25,
    prefix: '₹',
    decimals: 2,
    marketCap: '₹20.2L Cr',
    volume: '6.8M',
    high: 2999.0,
    low: 2951.2,
    about: 'Energy, retail and telecom conglomerate; the digital segment now anchors the growth narrative.',
    series: makeSeries(191, 0.14),
  },
  {
    symbol: 'TCS',
    pair: 'NSE',
    name: 'Tata Consultancy Services',
    category: 'Stocks',
    price: 4162.8,
    change: -0.62,
    prefix: '₹',
    decimals: 2,
    marketCap: '₹15.1L Cr',
    volume: '2.1M',
    high: 4198.5,
    low: 4140.0,
    about: 'India’s largest IT services exporter, with deal momentum concentrated in cloud modernisation.',
    series: makeSeries(197, -0.07),
  },
  {
    symbol: 'HDFCBANK',
    pair: 'NSE',
    name: 'HDFC Bank',
    category: 'Stocks',
    price: 1642.3,
    change: 0.88,
    prefix: '₹',
    decimals: 2,
    marketCap: '₹12.5L Cr',
    volume: '9.4M',
    high: 1651.0,
    low: 1628.5,
    about: 'India’s largest private-sector bank by assets, with deposit growth the key metric post-merger.',
    series: makeSeries(211, 0.1),
  },

  // ----------------------------------------------------------------- INDICES
  {
    symbol: 'NIFTY 50',
    pair: 'NSE',
    name: 'Nifty 50 Index',
    category: 'Indices',
    price: 24320.15,
    change: 1.1,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 24380.4,
    low: 24102.6,
    about: 'The benchmark for large-cap Indian equities, covering 50 companies across 13 sectors.',
    series: makeSeries(223, 0.12),
  },
  {
    symbol: 'SENSEX',
    pair: 'BSE',
    name: 'BSE Sensex 30',
    category: 'Indices',
    price: 79890.6,
    change: 0.95,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 80120.2,
    low: 79310.5,
    about: 'India’s oldest equity benchmark, tracking 30 financially sound companies on the BSE.',
    series: makeSeries(227, 0.1),
  },
  {
    symbol: 'S&P 500',
    pair: 'CBOE',
    name: 'US SPX 500',
    category: 'Indices',
    price: 5560.4,
    change: 0.85,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 5572.8,
    low: 5528.1,
    about: 'The broadest read on US large-cap performance, weighted by float-adjusted market capitalisation.',
    series: makeSeries(233, 0.09),
  },
  {
    symbol: 'NASDAQ',
    pair: 'NASDAQ',
    name: 'US Tech 100',
    category: 'Indices',
    price: 19840.2,
    change: 1.4,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 19902.5,
    low: 19588.4,
    about: 'The 100 largest non-financial companies listed on Nasdaq, heavily weighted toward technology.',
    series: makeSeries(239, 0.15),
  },
  {
    symbol: 'FTSE 100',
    pair: 'LSE',
    name: 'UK Index',
    category: 'Indices',
    price: 8210.3,
    change: -0.2,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 8238.6,
    low: 8194.2,
    about: 'The UK large-cap benchmark, with a heavy weighting toward energy, mining and financials.',
    series: makeSeries(251, -0.03),
  },
  {
    symbol: 'NIKKEI 225',
    pair: 'TSE',
    name: 'Japan Index',
    category: 'Indices',
    price: 38900.5,
    change: 1.75,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 39050.0,
    low: 38210.8,
    about: 'A price-weighted average of 225 leading companies on the Tokyo Stock Exchange.',
    series: makeSeries(257, 0.18),
  },
  {
    symbol: 'DAX',
    pair: 'XETRA',
    name: 'Germany 40',
    category: 'Indices',
    price: 18420.9,
    change: 0.42,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 18488.2,
    low: 18344.5,
    about: 'The 40 largest German companies by order-book volume and market capitalisation.',
    series: makeSeries(263, 0.05),
  },
  {
    symbol: 'HANG SENG',
    pair: 'HKEX',
    name: 'Hong Kong Index',
    category: 'Indices',
    price: 17640.2,
    change: -1.05,
    prefix: '',
    decimals: 2,
    marketCap: '—',
    volume: '—',
    high: 17840.6,
    low: 17590.1,
    about: 'The primary gauge of the Hong Kong market, dominated by financials and mainland-listed groups.',
    series: makeSeries(269, -0.11),
  },

  // ------------------------------------------------------------------- FOREX
  {
    symbol: 'USD/INR',
    pair: 'FX',
    name: 'US Dollar / Rupee',
    category: 'Forex',
    price: 83.95,
    change: 0.05,
    prefix: '₹',
    decimals: 4,
    marketCap: '—',
    volume: '$6.4B',
    high: 84.02,
    low: 83.88,
    about: 'The most-traded rupee pair, closely managed against sharp moves by the central bank.',
    series: makeSeries(271, 0.01),
  },
  {
    symbol: 'EUR/USD',
    pair: 'FX',
    name: 'Euro / US Dollar',
    category: 'Forex',
    price: 1.089,
    change: -0.15,
    prefix: '$',
    decimals: 4,
    marketCap: '—',
    volume: '$92.1B',
    high: 1.0921,
    low: 1.0874,
    about: 'The world’s most liquid currency pair, driven by the rate differential between the ECB and the Fed.',
    series: makeSeries(277, -0.02),
  },
  {
    symbol: 'GBP/USD',
    pair: 'FX',
    name: 'Pound / US Dollar',
    category: 'Forex',
    price: 1.284,
    change: 0.25,
    prefix: '$',
    decimals: 4,
    marketCap: '—',
    volume: '$38.4B',
    high: 1.2868,
    low: 1.2802,
    about: 'Sterling against the dollar — historically one of the more volatile of the major pairs.',
    series: makeSeries(281, 0.03),
  },
  {
    symbol: 'USD/JPY',
    pair: 'FX',
    name: 'US Dollar / Yen',
    category: 'Forex',
    price: 156.4,
    change: -0.4,
    prefix: '¥',
    decimals: 3,
    marketCap: '—',
    volume: '$54.2B',
    high: 157.1,
    low: 156.0,
    about: 'A classic carry-trade pair, highly sensitive to shifts in Bank of Japan policy guidance.',
    series: makeSeries(283, -0.04),
  },
  {
    symbol: 'AUD/USD',
    pair: 'FX',
    name: 'Aussie / US Dollar',
    category: 'Forex',
    price: 0.672,
    change: 0.3,
    prefix: '$',
    decimals: 4,
    marketCap: '—',
    volume: '$14.8B',
    high: 0.6742,
    low: 0.6698,
    about: 'Often traded as a proxy for commodity demand and Chinese industrial activity.',
    series: makeSeries(293, 0.03),
  },
  {
    symbol: 'USD/CAD',
    pair: 'FX',
    name: 'US Dollar / Loonie',
    category: 'Forex',
    price: 1.368,
    change: -0.1,
    prefix: '$',
    decimals: 4,
    marketCap: '—',
    volume: '$12.2B',
    high: 1.3712,
    low: 1.3664,
    about: 'Closely correlated with crude oil, given Canada’s energy export exposure.',
    series: makeSeries(307, -0.01),
  },
  {
    symbol: 'USD/AED',
    pair: 'FX',
    name: 'US Dollar / Dirham',
    category: 'Forex',
    price: 3.6725,
    change: 0.0,
    prefix: 'AED ',
    decimals: 4,
    marketCap: '—',
    volume: '$2.1B',
    high: 3.6726,
    low: 3.6724,
    about: 'A pegged pair — the dirham is fixed to the dollar, so movement is effectively nil.',
    series: makeSeries(311, 0),
  },
  {
    symbol: 'USD/SGD',
    pair: 'FX',
    name: 'US Dollar / Sing Dollar',
    category: 'Forex',
    price: 1.345,
    change: 0.12,
    prefix: '$',
    decimals: 4,
    marketCap: '—',
    volume: '$8.6B',
    high: 1.3468,
    low: 1.3432,
    about: 'Managed against a trade-weighted basket rather than a single currency target.',
    series: makeSeries(313, 0.01),
  },

  // ------------------------------------------------------------- COMMODITIES
  {
    symbol: 'GOLD',
    pair: 'XAU/USD',
    name: 'Gold Spot',
    category: 'Commodities',
    price: 2415.8,
    change: 0.65,
    prefix: '$',
    suffix: '/oz',
    decimals: 2,
    marketCap: '—',
    volume: '$142B',
    high: 2428.4,
    low: 2402.1,
    about: 'The classic reserve asset, bid up when real yields fall or geopolitical risk rises.',
    series: makeSeries(317, 0.08),
  },
  {
    symbol: 'SILVER',
    pair: 'XAG/USD',
    name: 'Silver Spot',
    category: 'Commodities',
    price: 31.2,
    change: 1.45,
    prefix: '$',
    suffix: '/oz',
    decimals: 2,
    marketCap: '—',
    volume: '$18.4B',
    high: 31.6,
    low: 30.7,
    about: 'Half precious metal, half industrial input — solar demand now moves the price meaningfully.',
    series: makeSeries(331, 0.15),
  },
  {
    symbol: 'CRUDE',
    pair: 'WTI',
    name: 'WTI Crude Oil',
    category: 'Commodities',
    price: 78.4,
    change: -1.85,
    prefix: '$',
    suffix: '/bbl',
    decimals: 2,
    marketCap: '—',
    volume: '$96.2B',
    high: 80.1,
    low: 78.0,
    about: 'The US benchmark grade, priced at Cushing, Oklahoma and sensitive to inventory reports.',
    series: makeSeries(337, -0.19),
  },
  {
    symbol: 'BRENT',
    pair: 'ICE',
    name: 'Brent Crude',
    category: 'Commodities',
    price: 82.15,
    change: -1.4,
    prefix: '$',
    suffix: '/bbl',
    decimals: 2,
    marketCap: '—',
    volume: '$88.9B',
    high: 83.7,
    low: 81.8,
    about: 'The global seaborne benchmark, used to price roughly two-thirds of internationally traded crude.',
    series: makeSeries(347, -0.14),
  },
  {
    symbol: 'NATGAS',
    pair: 'NYMEX',
    name: 'Natural Gas',
    category: 'Commodities',
    price: 2.45,
    change: 2.1,
    prefix: '$',
    suffix: '/MMBtu',
    decimals: 3,
    marketCap: '—',
    volume: '$12.4B',
    high: 2.51,
    low: 2.39,
    about: 'Highly seasonal and storage-driven; weather forecasts move this contract more than anything else.',
    series: makeSeries(349, 0.21),
  },
  {
    symbol: 'COPPER',
    pair: 'COMEX',
    name: 'Copper Futures',
    category: 'Commodities',
    price: 4.52,
    change: 0.9,
    prefix: '$',
    suffix: '/lb',
    decimals: 3,
    marketCap: '—',
    volume: '$9.8B',
    high: 4.56,
    low: 4.48,
    about: 'Widely read as a barometer of global industrial demand and grid electrification.',
    series: makeSeries(353, 0.09),
  },
  {
    symbol: 'WHEAT',
    pair: 'CBOT',
    name: 'Wheat Futures',
    category: 'Commodities',
    price: 5.86,
    change: -0.75,
    prefix: '$',
    suffix: '/bu',
    decimals: 3,
    marketCap: '—',
    volume: '$3.2B',
    high: 5.94,
    low: 5.82,
    about: 'Driven by harvest conditions in the Black Sea region, North America and Australia.',
    series: makeSeries(359, -0.08),
  },
  {
    symbol: 'PLATINUM',
    pair: 'XPT/USD',
    name: 'Platinum Spot',
    category: 'Commodities',
    price: 964.3,
    change: 1.15,
    prefix: '$',
    suffix: '/oz',
    decimals: 2,
    marketCap: '—',
    volume: '$2.8B',
    high: 972.5,
    low: 954.0,
    about: 'Concentrated supply from South Africa, with autocatalyst demand the swing factor.',
    series: makeSeries(367, 0.12),
  },
]

/** Mid-market rates against 1 USD, used by the converter. */
export const fxRates = {
  USD: { rate: 1, symbol: '$', label: 'US Dollar' },
  INR: { rate: 83.95, symbol: '₹', label: 'Indian Rupee' },
  EUR: { rate: 0.918, symbol: '€', label: 'Euro' },
  GBP: { rate: 0.779, symbol: '£', label: 'British Pound' },
  JPY: { rate: 156.4, symbol: '¥', label: 'Japanese Yen' },
  AED: { rate: 3.6725, symbol: 'AED ', label: 'UAE Dirham' },
  AUD: { rate: 1.488, symbol: 'A$', label: 'Australian Dollar' },
  CAD: { rate: 1.368, symbol: 'C$', label: 'Canadian Dollar' },
  SGD: { rate: 1.345, symbol: 'S$', label: 'Singapore Dollar' },
  CHF: { rate: 0.882, symbol: 'CHF ', label: 'Swiss Franc' },
}

export const economicCalendar = [
  { time: '09:15', region: 'IN', event: 'RBI monetary policy statement', impact: 'High', forecast: '6.50%', previous: '6.50%' },
  { time: '11:30', region: 'EU', event: 'Eurozone flash CPI (YoY)', impact: 'High', forecast: '2.4%', previous: '2.6%' },
  { time: '13:00', region: 'UK', event: 'BoE rate decision', impact: 'High', forecast: '5.00%', previous: '5.25%' },
  { time: '18:00', region: 'US', event: 'Non-farm payrolls', impact: 'High', forecast: '185K', previous: '206K' },
  { time: '18:00', region: 'US', event: 'Unemployment rate', impact: 'Medium', forecast: '4.1%', previous: '4.1%' },
  { time: '20:00', region: 'US', event: 'Crude oil inventories', impact: 'Medium', forecast: '-2.1M', previous: '-3.4M' },
  { time: '21:30', region: 'US', event: 'Fed chair press conference', impact: 'High', forecast: '—', previous: '—' },
  { time: '05:30', region: 'JP', event: 'BoJ policy minutes', impact: 'Low', forecast: '—', previous: '—' },
  { time: '07:00', region: 'CN', event: 'Manufacturing PMI', impact: 'Medium', forecast: '49.8', previous: '49.5' },
  { time: '16:00', region: 'DE', event: 'Industrial production (MoM)', impact: 'Low', forecast: '0.3%', previous: '-0.1%' },
]

export const marketTools = [
  {
    title: 'Watchlists that live in chat',
    desc: 'Pin up to 100 instruments. Your list syncs across devices and can be shared into a group with one tap.',
  },
  {
    title: 'Price alerts by message',
    desc: 'Set a level and KT AI messages you the moment it prints — no separate app, no push-notification noise.',
  },
  {
    title: 'Interbank FX conversion',
    desc: 'Convert between ten currencies at mid-market rates. What you see is the rate used, with no hidden spread.',
  },
  {
    title: 'Portfolio tracking',
    desc: 'Add holdings once and follow day P/L, allocation and exposure without linking a brokerage account.',
  },
  {
    title: 'Economic calendar',
    desc: 'Every scheduled release that moves markets, with forecast and prior values, in your local time zone.',
  },
  {
    title: 'Sector heatmap',
    desc: 'One glance tells you what is working today. Tap any tile to open the full instrument card.',
  },
  {
    title: 'Earnings digests',
    desc: 'Results summarised into five bullet points within minutes of the release hitting the wire.',
  },
  {
    title: 'Shared group watchlists',
    desc: 'Investment clubs and desks can follow one list together, with changes visible to every member.',
  },
  {
    title: 'Export to spreadsheet',
    desc: 'Download any watchlist or portfolio as CSV whenever you want it — your data stays portable.',
  },
]

export const marketSteps = [
  { title: 'Search an instrument', desc: 'Find any of 44 assets across crypto, equities, indices, FX and commodities.' },
  { title: 'Star it to your watchlist', desc: 'Your list syncs encrypted across every device signed in to your account.' },
  { title: 'Set the alert level', desc: 'Choose above or below a price and KT AI messages you the moment it triggers.' },
  { title: 'Act or share', desc: 'Forward the instrument card into a group chat, or export the list as a spreadsheet.' },
]

export const marketLearn = [
  {
    title: 'What actually moves a currency pair',
    minutes: 6,
    level: 'Beginner',
    desc: 'Rate differentials, trade balance and risk sentiment — and why the third one overrides the other two in a crisis.',
  },
  {
    title: 'Reading a candlestick without fooling yourself',
    minutes: 8,
    level: 'Beginner',
    desc: 'What a candle does and does not tell you, plus the three patterns that survive statistical scrutiny.',
  },
  {
    title: 'Market cap versus fully diluted valuation',
    minutes: 5,
    level: 'Intermediate',
    desc: 'Why a token can look cheap on one metric and expensive on the other, and which one to trust when.',
  },
  {
    title: 'Position sizing before entry',
    minutes: 7,
    level: 'Intermediate',
    desc: 'Deciding how much to risk before you decide what to buy — the single habit that separates outcomes.',
  },
  {
    title: 'How index weighting distorts a benchmark',
    minutes: 6,
    level: 'Intermediate',
    desc: 'Price-weighted, cap-weighted and equal-weighted indices tell three different stories about the same market.',
  },
  {
    title: 'Reading an economic calendar',
    minutes: 4,
    level: 'Beginner',
    desc: 'Forecast, prior and revision — which of the three actually moves the price on release.',
  },
]

export const marketFaqs = [
  {
    q: 'Are the prices on this page live?',
    a: 'The figures shown here are illustrative sample data for the product page. Inside the app, feeds stream from licensed liquidity providers with a visible timestamp on every quote.',
    tag: 'Data',
  },
  {
    q: 'Can I trade directly from KT Markets?',
    a: 'No. KT Markets is a tracking and alerting surface — watchlists, conversion and portfolio views. It does not execute orders and does not hold your assets.',
    tag: 'Scope',
  },
  {
    q: 'How do price alerts reach me?',
    a: 'As an ordinary encrypted message in your KT chat. Set a level, pick above or below, and the alert fires once the condition is met.',
    tag: 'Alerts',
  },
  {
    q: 'What exchange rate does the converter use?',
    a: 'Mid-market interbank rates with no markup applied. The rate used in the calculation is the rate displayed — nothing is added behind the scenes.',
    tag: 'FX',
  },
  {
    q: 'Does adding holdings connect to my broker?',
    a: 'No. The portfolio view is manual by design: you enter quantities, and nothing is linked to a brokerage or exchange account.',
    tag: 'Portfolio',
  },
  {
    q: 'Is my watchlist visible to anyone else?',
    a: 'Only to you, unless you explicitly share a list into a group. Watchlists are stored encrypted and are not used for advertising.',
    tag: 'Privacy',
  },
  {
    q: 'Which markets are covered?',
    a: 'Major crypto assets, US and Indian equities, eight global indices, the main FX pairs and eight commodities — 44 instruments in total on this page.',
    tag: 'Coverage',
  },
  {
    q: 'Do you provide investment advice?',
    a: 'No. Nothing here is a recommendation. Prices, digests and educational articles are informational, and you should consult a licensed adviser before investing.',
    tag: 'Disclaimer',
  },
  {
    q: 'Can I export my data?',
    a: 'Yes. Any watchlist or portfolio exports to CSV on demand, and you can delete the underlying data at any time.',
    tag: 'Data',
  },
  {
    q: 'How often does the heatmap refresh?',
    a: 'Every few seconds during market hours, and it switches to last-close values once a market shuts for the day.',
    tag: 'Data',
  },
]

export const marketTestimonials = [
  {
    quote: 'The alert lands as a message, so I actually see it. Every other app’s notification got muted months ago.',
    name: 'Karthik Nair',
    role: 'Options trader, Chennai',
  },
  {
    quote: 'Mid-market FX with no spread is the whole reason I use this before sending money abroad.',
    name: 'Sarah Lindqvist',
    role: 'Freelance developer, Malmö',
  },
  {
    quote: 'Our investment club runs one shared watchlist. Debating a position in the same thread just works.',
    name: 'Daniel Mwangi',
    role: 'Club treasurer, Nairobi',
  },
  {
    quote: 'The heatmap is the first thing I open. Thirty seconds and I know what kind of day it is.',
    name: 'Yuki Nakamura',
    role: 'Portfolio analyst, Tokyo',
  },
  {
    quote: 'Manual portfolio entry sounded like a downside until I realised nothing is linked to my broker.',
    name: 'Priyanka Shah',
    role: 'Product designer, Mumbai',
  },
  {
    quote: 'The calendar with forecast and prior values saved me from trading straight into a rate decision.',
    name: 'Miguel Torres',
    role: 'Retail investor, Madrid',
  },
]
