import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { FiPlay, FiPause, FiRotateCcw, FiCpu, FiImage, FiSend } from 'react-icons/fi'
import astronautUnicornImage from '../../../assets/images/astronaut_unicorn_mars.png'

function SparklesIcon({ className = 'h-4 w-4' }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 0C12 6.627 6.627 12 0 12C6.627 12 12 17.373 12 24C12 17.373 17.373 12 24 12C17.373 12 12 6.627 12 0Z" />
    </svg>
  )
}

export function AiAnimationVideo({ className = '' }) {
  const [isPlaying, setIsPlaying] = useState(true)
  const [step, setStep] = useState(0) // 0: Typing prompt, 1: AI Generating, 2: Result rendered
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (!isPlaying) return

    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          setStep(0)
          return 0
        }
        const next = prev + 1.25
        if (next > 30 && next <= 60) setStep(1)
        else if (next > 60) setStep(2)
        return next
      })
    }, 100)

    return () => clearInterval(interval)
  }, [isPlaying])

  const restartVideo = () => {
    setStep(0)
    setProgress(0)
    setIsPlaying(true)
  }

  return (
    <div className={`overflow-hidden rounded-3xl border border-line bg-surface p-4 shadow-float ${className}`}>
      {/* Video Player Header Bar */}
      <div className="flex items-center justify-between border-b border-line pb-3 mb-3">
        <div className="flex items-center gap-2">
          <span className="flex h-3 w-3 rounded-full bg-brand-strong animate-pulse" />
          <span className="text-xs font-bold text-ink uppercase tracking-wider">Video Clip • How KT AI Assistant Works</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsPlaying(!isPlaying)}
            className="flex items-center gap-1 rounded-full bg-brand-soft px-3 py-1 text-xs font-bold text-brand-ink hover:bg-brand-strong hover:text-white transition-colors"
          >
            {isPlaying ? <><FiPause /> Pause</> : <><FiPlay /> Play</>}
          </button>
          <button
            onClick={restartVideo}
            className="grid h-7 w-7 place-items-center rounded-full bg-cream text-ink hover:bg-line text-xs"
            title="Replay video"
          >
            <FiRotateCcw />
          </button>
        </div>
      </div>

      {/* Video Screen Viewport */}
      <div className="relative aspect-[16/10] w-full overflow-hidden rounded-2xl bg-slate-950 p-4 border border-slate-800 flex flex-col justify-between text-white">
        <div className="flex items-center gap-2 border-b border-slate-800 pb-2">
          <SparklesIcon className="text-sky-400 text-lg" />
          <span className="text-xs font-bold">KT AI Multimodal Assistant</span>
        </div>

        {step === 0 && (
          <div className="my-auto rounded-xl bg-slate-900 p-3 text-xs border border-slate-800">
            <span className="font-bold text-sky-400">/imagine</span> An astronaut riding a unicorn on Mars 🦄
          </div>
        )}

        {step === 1 && (
          <div className="my-auto text-center space-y-2.5 py-3">
            <div className="relative mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-tr from-sky-500 via-indigo-600 to-purple-600 text-white shadow-lg shadow-sky-500/30">
              <span className="absolute -inset-1 rounded-2xl bg-sky-400/40 blur-sm animate-pulse" />
              <SparklesIcon className="relative z-10 h-6 w-6 animate-pulse text-white" />
            </div>
            <p className="text-xs font-bold text-sky-400 uppercase tracking-wider">KT AI GPU rendering 4K image...</p>
          </div>
        )}

        {step === 2 && (
          <div className="relative h-full w-full overflow-hidden rounded-xl bg-slate-900 border border-slate-800 mt-2">
            <img src={astronautUnicornImage} alt="AI Artwork" className="h-full w-full object-cover" />
            <div className="absolute bottom-2 left-2 rounded-md bg-black/70 px-2 py-0.5 text-[9px] font-bold text-white backdrop-blur-md">
              Generated by KT AI ✨
            </div>
          </div>
        )}
      </div>

      {/* Video Progress Scrubber */}
      <div className="mt-3 flex items-center gap-3">
        <div className="h-1.5 flex-1 rounded-full bg-cream overflow-hidden border border-line">
          <div style={{ width: `${progress}%` }} className="h-full bg-brand-strong transition-all duration-100" />
        </div>
        <span className="font-mono text-[10px] font-bold text-muted">
          0:0{Math.floor((progress / 100) * 15)} / 0:15s
        </span>
      </div>
    </div>
  )
}
