import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { PhoneVideoFrame } from './PhoneVideoFrame'
import sunsetImage from '../../../assets/images/sunset_landscape.png'

function SparklesIcon({ className = 'h-4 w-4' }) {
  return (
    <svg className={className} fill="currentColor" viewBox="0 0 16 16">
      <path d="M7.5 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm0 12a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm7.5-6.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 1 .5.5zm-12 0a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 1 .5.5zm10.243-4.243a.5.5 0 0 1 0 .707l-2.122 2.121a.5.5 0 1 1-.707-.707l2.122-2.121a.5.5 0 0 1 .707 0zm-8.486 8.485a.5.5 0 0 1 0 .707l-2.121 2.122a.5.5 0 1 1-.707-.707l2.121-2.122a.5.5 0 0 1 .707 0zm0-8.485a.5.5 0 0 1 .707 0l2.121 2.121a.5.5 0 1 1-.707.707L4.257 3.515a.5.5 0 0 1 0-.707zm8.486 8.485a.5.5 0 0 1 .707 0l2.121 2.122a.5.5 0 1 1-.707.707l-2.121-2.122a.5.5 0 0 1 0-.707z" />
    </svg>
  )
}

export function KtAiLoopVideo({ className = '' }) {
  const [isPlaying, setIsPlaying] = useState(true)
  const [phase, setPhase] = useState(0) // 0: Prompt typing, 1: Generating, 2: 4K Render Result
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (!isPlaying) return

    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          setPhase(0)
          return 0
        }
        const next = prev + 1.5
        if (next > 30 && next <= 60) setPhase(1)
        else if (next > 60) setPhase(2)
        return next
      })
    }, 100)

    return () => clearInterval(interval)
  }, [isPlaying])

  const restartVideo = () => {
    setPhase(0)
    setProgress(0)
    setIsPlaying(true)
  }

  return (
    <PhoneVideoFrame
      title="KT AI Image &amp; Text Studio"
      progress={progress}
      isPlaying={isPlaying}
      onTogglePlay={() => setIsPlaying(!isPlaying)}
      onRestart={restartVideo}
      className={className}
    >
      {/* Mobile AI Header */}
      <div className="flex items-center gap-2 border-b border-white/10 pb-2">
        <SparklesIcon className="text-brand-strong text-base" />
        <span className="text-xs font-bold text-white">KT AI Assistant Engine</span>
      </div>

      {/* Screen Stream */}
      <div className="my-auto relative h-full flex flex-col justify-center py-1">
        {phase === 0 && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="my-auto rounded-xl bg-slate-950 p-2.5 text-xs border border-slate-800">
            <span className="font-bold text-brand-strong">/imagine</span> An astronaut riding a unicorn on Mars 🦄
          </motion.div>
        )}

        {phase === 1 && (
          <div className="my-auto text-center space-y-2">
            <SparklesIcon className="animate-spin text-2xl mx-auto text-brand-strong" />
            <p className="text-[11px] font-semibold text-slate-200">KT AI Neural GPU rendering 4K image...</p>
          </div>
        )}

        {phase === 2 && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="relative h-full w-full overflow-hidden rounded-xl bg-slate-950 border border-slate-800 my-auto">
            <img src={sunsetImage} alt="AI Artwork" className="h-full w-full object-cover" />
            <div className="absolute bottom-2 left-2 rounded-md bg-black/70 px-2 py-0.5 text-[8px] font-bold text-white backdrop-blur-md">
              Generated by KT AI ✨
            </div>
          </motion.div>
        )}
      </div>

      {/* Screen Footer */}
      <div className="rounded-xl bg-slate-950 p-1.5 text-center text-[9px] font-bold text-brand-ink border border-slate-800">
        Generate 4K artwork &amp; answer questions instantly in chat
      </div>
    </PhoneVideoFrame>
  )
}
