import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { PhoneVideoFrame } from './PhoneVideoFrame'
import astronautUnicornImage from '../../../assets/images/astronaut_unicorn_mars.png'

function SparklesIcon({ className = '' }) {
  return (
    <svg className={`h-4 w-4 shrink-0 ${className}`} viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 0C12 6.627 6.627 12 0 12C6.627 12 12 17.373 12 24C12 17.373 17.373 12 24 12C17.373 12 12 6.627 12 0Z" />
    </svg>
  )
}

export function KtAiLoopVideo({ className = '' }) {
  const [isPlaying, setIsPlaying] = useState(true)
  const [phase, setPhase] = useState(0) // 0: Prompt typing, 1: Generating, 2: 4K Render Result
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (!isPlaying) return

    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          setPhase(0)
          return 0
        }
        const next = prev + 1.5
        if (next > 30 && next <= 60) setPhase(1)
        else if (next > 60) setPhase(2)
        return next
      })
    }, 100)

    return () => clearInterval(interval)
  }, [isPlaying])

  const restartVideo = () => {
    setPhase(0)
    setProgress(0)
    setIsPlaying(true)
  }

  return (
    <PhoneVideoFrame
      title="KT AI Image &amp; Text Studio"
      progress={progress}
      isPlaying={isPlaying}
      onTogglePlay={() => setIsPlaying(!isPlaying)}
      onRestart={restartVideo}
      className={className}
    >
      {/* Mobile AI Header */}
      <div className="flex items-center gap-2 border-b border-white/10 pb-2">
        <SparklesIcon className="text-sky-400 text-base" />
        <span className="text-xs font-bold text-white">KT AI Assistant Engine</span>
      </div>

      {/* Screen Stream */}
      <div className="my-auto relative h-full flex flex-col justify-center py-1">
        {phase === 0 && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="my-auto rounded-xl bg-slate-950 p-2.5 text-xs border border-slate-800">
            <span className="font-bold text-sky-400">/imagine</span> An astronaut riding a unicorn on Mars 🦄
          </motion.div>
        )}

        {phase === 1 && (
          <div className="my-auto text-center space-y-2.5 py-4">
            <div className="relative mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-tr from-sky-500 via-indigo-600 to-purple-600 text-white shadow-lg shadow-sky-500/30">
              <span className="absolute -inset-1 rounded-2xl bg-sky-400/40 blur-sm animate-pulse" />
              <SparklesIcon className="relative z-10 h-7 w-7 animate-pulse text-white" />
            </div>
            <p className="text-[11px] font-bold text-sky-400 uppercase tracking-wider">KT AI Neural GPU rendering 4K image...</p>
          </div>
        )}

        {phase === 2 && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="relative h-full w-full overflow-hidden rounded-xl bg-slate-950 border border-slate-800 my-auto">
            <img src={astronautUnicornImage} alt="AI Artwork" className="h-full w-full object-cover" />
            <div className="absolute bottom-2 left-2 rounded-md bg-black/70 px-2 py-0.5 text-[8px] font-bold text-white backdrop-blur-md">
              Generated by KT AI ✨
            </div>
          </motion.div>
        )}
      </div>

      {/* Screen Footer */}
      <div className="rounded-xl bg-slate-950 p-1.5 text-center text-[9px] font-bold text-sky-400 border border-slate-800">
        Generate 4K artwork &amp; answer questions instantly in chat
      </div>
    </PhoneVideoFrame>
  )
}
