// ---------------------------------------------------------------------------
// KT News — page content.
// Kept out of the page component so the JSX stays readable and the copy is
// easy to edit in one place.
// ---------------------------------------------------------------------------

export const newsCategories = [
  'All News',
  'Tech & AI',
  'Business & Markets',
  'Crypto & Web3',
  'Global Headlines',
  'Science & Climate',
  'Entertainment',
]

export const breakingTicker = [
  'ITU adopts universal end-to-end encryption standard for all consumer messaging',
  'KT AI Co-Pilot crosses 500M daily assistant queries across 120 countries',
  'Fusion reactor sustains 100MW clean output for 12 straight hours',
  'Bitcoin holds above $67,400 as zero-fee in-chat wallets go live',
  'LEO satellite direct-to-cellular messaging enters global beta',
  'Esports World Cup final draws record 85M concurrent viewers',
  'Direct air capture plant begins removing 1M tons of CO₂ a year',
]

export const newsArticles = [
  // ---------------------------------------------------------------- TECH & AI
  {
    id: 1,
    category: 'Tech & AI',
    title: 'KT AI Co-Pilot Reaches 500 Million Active Daily Assistant Queries',
    summary:
      'The native Signal-encrypted AI assistant now powers real-time language translation and image creation for users across 120 countries.',
    body: [
      'KT Messengers announced today that its built-in KT AI Co-Pilot has surpassed 500 million daily active assistant queries worldwide, roughly triple the volume recorded at the start of the year.',
      'Powered by ultra-low-latency neural networks that run partly on-device, the assistant handles instant message translation across 50+ languages, automated business replies, long-document summaries and high-fidelity text-to-image generation without leaving a private chat thread.',
      'Crucially, the company says prompt content never leaves the encrypted envelope: requests are processed inside a sealed enclave and the plaintext is discarded the moment a response is returned. Independent auditors have been given read access to the enclave attestation logs.',
    ],
    author: 'Priya Raman',
    source: 'TechCrunch',
    time: '10 mins ago',
    readMins: 4,
    reads: '18.4k',
    tags: ['AI', 'Assistants', 'Privacy'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 2,
    category: 'Tech & AI',
    title: 'Next-Gen Quantum Mesh Encryption Applied to Mobile Messaging',
    summary:
      'Cybersecurity engineers demonstrate post-quantum lattice cryptography running natively on mainstream smartphone hardware.',
    body: [
      'A breakthrough in mobile cryptographic performance has allowed quantum-resistant lattice algorithms to complete a full handshake in under two milliseconds on mid-range hardware.',
      'The update means message transmissions stay sealed even against a future adversary that harvests traffic today and decrypts it once large-scale quantum computers arrive — the so-called "store now, decrypt later" threat.',
      'Rollout is staged: new conversations negotiate the hybrid cipher automatically, while existing threads upgrade during their next scheduled key rotation.',
    ],
    author: 'Daniel Okoye',
    source: 'Wired Tech',
    time: '25 mins ago',
    readMins: 5,
    reads: '12.1k',
    tags: ['Security', 'Quantum', 'Cryptography'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    category: 'Tech & AI',
    title: 'Autonomous AI Agents Take Over Multi-Party Project Coordination',
    summary: 'Enterprise teams report 70% faster task resolution using agents embedded inside KT group workspaces.',
    body: [
      'Autonomous AI sub-agents are quietly redefining team collaboration. By monitoring chat deadlines, scheduling calls and compiling meeting minutes, they remove the coordination overhead that usually falls on a project lead.',
      'In a survey of 400 enterprise workspaces, teams reported saving an average of 15 hours per employee per week, with the biggest gains in distributed teams spanning three or more time zones.',
      'The agents operate under explicit scopes: an agent can read the thread it was invited to and nothing else, and every action it takes is written to a visible audit trail inside the group.',
    ],
    author: 'Lena Fischer',
    source: 'MIT Tech Review',
    time: '1 hour ago',
    readMins: 6,
    reads: '9.5k',
    tags: ['AI Agents', 'Teams', 'Productivity'],
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    category: 'Tech & AI',
    title: 'AR Spatial Video Calling Rolls Out to 100 Million Mobile Devices',
    summary: 'Spatial audio and 3D depth rendering make virtual meetings feel closer to face-to-face conversation.',
    body: [
      'With the latest mobile SDK update, KT Messengers has introduced spatial AR calling. Participants appear in 3D perspective space with positional audio that tracks where each person sits in the virtual room.',
      'Early testers describe a marked drop in the "talking over each other" problem that plagues flat grid calls, because directional audio gives the brain the same turn-taking cues it uses in a physical room.',
      'The feature degrades gracefully: on devices without depth sensors the call falls back to a standard 2D grid with spatial audio preserved.',
    ],
    author: 'Marcus Bell',
    source: 'The Verge',
    time: '2 hours ago',
    readMins: 4,
    reads: '22.8k',
    tags: ['AR', 'Calling', 'Hardware'],
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    category: 'Tech & AI',
    title: 'Open Source Neural Code Generators Achieve 98% Syntactic Accuracy',
    summary: 'Developers build full-stack applications inside chat channels using conversational coding prompts.',
    body: [
      'AI pair programming has expanded into messaging platforms. Developers can execute terminal commands, edit component trees and deploy applications without leaving their KT desktop client.',
      'The measured 98% figure covers syntactic validity rather than semantic correctness — code that compiles is not automatically code that is right, and maintainers stress that review still matters.',
      'The models ship under a permissive licence, and the training corpus manifest is published alongside each release so teams can check provenance before adopting them.',
    ],
    author: 'Sofia Almeida',
    source: 'GitHub Blog',
    time: '3 hours ago',
    readMins: 5,
    reads: '14.6k',
    tags: ['Developers', 'Open Source', 'AI'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    category: 'Tech & AI',
    title: 'Neuromorphic Microchips Double Battery Life During On-Device AI Work',
    summary: 'Manufacturers ship ultra-efficient NPU architectures tuned for local language-model inference.',
    body: [
      'By shifting AI workloads onto neuromorphic micro-cores, device battery consumption drops by roughly 65% during continuous voice translation and real-time image processing.',
      'The architecture trades peak throughput for efficiency, which suits the bursty, always-listening workloads a messaging assistant actually runs.',
      'Because inference stays on the handset, transcripts of voice notes never traverse the network — a privacy win that arrives as a side effect of a power optimisation.',
    ],
    author: 'Hiroshi Tanaka',
    source: 'AnandTech',
    time: '4 hours ago',
    readMins: 6,
    reads: '11.2k',
    tags: ['Silicon', 'Battery', 'On-device AI'],
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    category: 'Tech & AI',
    title: '6G Satellite Direct-to-Cellular Networks Enter Global Beta Testing',
    summary: 'Messaging connectivity reaches ocean vessels and remote mountain regions without a single cell tower.',
    body: [
      'Low Earth Orbit satellite constellations now bridge communication gaps in dead zones worldwide. Standard smartphones — no special antenna — maintain encrypted messaging in remote wilderness areas.',
      'Bandwidth is deliberately modest: text, location pings and compressed voice notes are prioritised, while video is queued until a terrestrial network is available.',
      'Emergency services are the first cohort in the beta, with search-and-rescue teams in three countries already running field trials.',
    ],
    author: 'Elena Vasquez',
    source: 'SpaceNews',
    time: '5 hours ago',
    readMins: 5,
    reads: '31.0k',
    tags: ['Satellite', '6G', 'Connectivity'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 8,
    category: 'Tech & AI',
    title: 'Synthetic Voice Verification Protocols Defeat Deepfake Scams',
    summary: 'Cryptographic voiceprints let recipients confirm an audio note really came from the sender.',
    body: [
      'To counter deepfake audio impersonation, KT Messengers now attaches a cryptographic signature to every voice note, generated by the sender device key.',
      'Audio arriving without a valid signature displays a prominent warning badge — a small interface change that closes off one of the fastest-growing categories of financial fraud.',
      'The signature covers the waveform itself, so re-encoding or trimming a clip invalidates it rather than silently passing verification.',
    ],
    author: 'Grace Whitfield',
    source: 'ZDNet',
    time: '6 hours ago',
    readMins: 4,
    reads: '16.9k',
    tags: ['Deepfakes', 'Voice', 'Fraud'],
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
  },

  // ------------------------------------------------------ BUSINESS & MARKETS
  {
    id: 9,
    category: 'Business & Markets',
    title: 'Global E-Commerce Sales Surge as In-Chat Payments Open Up',
    summary: 'Retailers report a 340% lift in checkout conversion using chat catalogs and one-tap UPI flows.',
    body: [
      'Merchants using conversational commerce tools on KT Messengers are seeing unusually strong growth. Removing the jump between product discovery and checkout appears to be the single biggest factor.',
      'The 340% figure compares chat checkout against the same merchants’ own web storefronts over a matched 90-day window, so it controls for seasonality and catalogue differences.',
      'Analysts caution that the effect is strongest for low-consideration purchases under ₹5,000; high-ticket categories still show a long research tail.',
    ],
    author: 'Aditya Menon',
    source: 'Bloomberg Business',
    time: '35 mins ago',
    readMins: 5,
    reads: '15.4k',
    tags: ['E-commerce', 'Payments', 'Retail'],
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 10,
    category: 'Business & Markets',
    title: 'Central Banks Accelerate Digital Currency Integration into Chat Apps',
    summary: 'CBDC cross-border settlement cuts remittance costs by up to 95% for migrant workers.',
    body: [
      'Partnerships between central monetary authorities and secure messaging platforms have enabled near-zero-cost cross-border remittances with real-time conversion.',
      'For a worker sending ₹20,000 home each month, the fee saving compounds to a meaningful annual sum — the World Bank has long flagged remittance costs as a regressive tax on the lowest earners.',
      'Regulators emphasise that transaction limits and identity checks remain unchanged; only the settlement rail is new.',
    ],
    author: 'Claire Dubois',
    source: 'Financial Times',
    time: '1 hour ago',
    readMins: 6,
    reads: '19.2k',
    tags: ['CBDC', 'Remittance', 'Policy'],
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 11,
    category: 'Business & Markets',
    title: 'SaaS Subscriptions Shift to Conversational Bot Interfaces',
    summary: 'Companies retire legacy dashboards in favour of workflow bots that live in the team chat.',
    body: [
      'Enterprise software usage is moving into messaging channels. Approvals, expense tracking, HR onboarding and CRM updates now run as natural-language commands inside group threads.',
      'The pattern favours tools that do one thing per message. Vendors that ported an entire dashboard into a bot reported worse adoption than those that shipped three well-chosen commands.',
      'Seat costs are falling as a result, since occasional users no longer need a full licence just to approve a request.',
    ],
    author: 'Tom Rivera',
    source: 'Forbes',
    time: '2 hours ago',
    readMins: 4,
    reads: '8.7k',
    tags: ['SaaS', 'Bots', 'Enterprise'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 12,
    category: 'Business & Markets',
    title: 'Trading Volume Hits Record Highs via Mobile API Webhooks',
    summary: 'Retail participation climbs as real-time ticker bots broadcast instant earnings alerts.',
    body: [
      'Instant market intelligence feeds are reshaping how retail investors react to news. Channels broadcasting earnings and analyst sentiment grew subscribers 220% this quarter.',
      'Exchanges note that faster information flow has narrowed the gap between institutional and retail reaction times, though it has also increased intraday volatility around scheduled releases.',
      'Consumer-protection groups are pressing for clearer labelling of promotional content inside finance channels.',
    ],
    author: 'Nina Kaur',
    source: 'Wall Street Journal',
    time: '3 hours ago',
    readMins: 5,
    reads: '27.4k',
    tags: ['Markets', 'Retail Investing', 'APIs'],
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 13,
    category: 'Business & Markets',
    title: 'Venture Funding Surges for Decentralized Messaging Infrastructure',
    summary: 'Investors commit $4.2 billion to zero-knowledge communication protocols and identity vaults.',
    body: [
      'Privacy-focused infrastructure remains the top investment sector for global venture firms this year, ahead of both climate tech and enterprise AI tooling.',
      'Networks that guarantee zero metadata collection are securing record Series B rounds, driven by enterprise demand rather than consumer pull.',
      'Sceptics point out that revenue models for pure-protocol companies remain unproven, and that several 2021-vintage peers have already wound down.',
    ],
    author: 'Priya Raman',
    source: 'TechCrunch',
    time: '4 hours ago',
    readMins: 4,
    reads: '13.8k',
    tags: ['Venture Capital', 'Privacy', 'Funding'],
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 14,
    category: 'Business & Markets',
    title: 'Supply Chains Tracked in Real Time via Encrypted Sensor Bots',
    summary: 'Shipping containers broadcast GPS and temperature logs straight into logistics group chats.',
    body: [
      'Freight forwarders now receive automated sensor alerts inside KT group channels whenever cargo temperature or humidity drifts outside safe parameters.',
      'For pharmaceutical and fresh-produce shipments, the difference between a four-hour and a four-day notification is often the difference between a salvaged and a written-off load.',
      'Sensor payloads are signed at the device, so a tampered reading fails verification before it reaches the operations team.',
    ],
    author: 'Ravi Deshmukh',
    source: 'Reuters Logistics',
    time: '5 hours ago',
    readMins: 5,
    reads: '10.3k',
    tags: ['Logistics', 'IoT', 'Supply Chain'],
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 15,
    category: 'Business & Markets',
    title: 'Micro-Businesses Grow Revenue 500% Using Automated Catalog Bots',
    summary: 'Artisan shops and home bakeries run orders, payments and delivery scheduling entirely in chat.',
    body: [
      'Solo entrepreneurs are adopting conversational commerce at scale. An embedded product catalogue lets a one-person shop take orders around the clock without an e-commerce site.',
      'The lowest-friction setup wins: sellers who published fewer than 20 SKUs with clear photos consistently outperformed those who uploaded their entire inventory.',
      'Payment settlement lands next business day, which sellers cite as the main reason they moved off social-media DMs.',
    ],
    author: 'Meera Joshi',
    source: 'Entrepreneur',
    time: '6 hours ago',
    readMins: 4,
    reads: '21.5k',
    tags: ['Small Business', 'Commerce', 'Growth'],
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
  },

  // ------------------------------------------------------------ CRYPTO & WEB3
  {
    id: 16,
    category: 'Crypto & Web3',
    title: 'Bitcoin Crosses New Milestone as Zero-Fee Web3 Wallets Roll Out',
    summary: 'Store, send and swap tokens natively inside KT Wallet with hardware-level passkey protection.',
    body: [
      'Native non-custodial wallet support inside messaging apps has accelerated digital asset adoption, particularly among users who never installed a standalone wallet.',
      'KT Wallet users can execute zero-gas token transfers backed by hardware passkey security, with the signing key held in the device secure element.',
      'Non-custodial means exactly that: the platform cannot move funds, and it cannot restore them if a user loses every recovery share.',
    ],
    author: 'Jonas Weber',
    source: 'CoinDesk',
    time: '45 mins ago',
    readMins: 5,
    reads: '38.5k',
    tags: ['Bitcoin', 'Wallets', 'Web3'],
    image: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 17,
    category: 'Crypto & Web3',
    title: 'Ethereum Layer-2 Networks Process 100,000 Transactions Per Second',
    summary: 'Zero-knowledge rollups flatten gas spikes, making micro-tipping viable inside creator channels.',
    body: [
      'Scalability bottlenecks that once defined public blockchains have eased considerably. Rollup architectures let creators receive sub-cent tips instantly during live broadcasts.',
      'Throughput figures are measured under benchmark conditions; real-world sustained rates sit meaningfully lower but still comfortably above payment-network requirements.',
      'Withdrawal latency back to the base layer remains the main user-experience gap.',
    ],
    author: 'Ayesha Khan',
    source: 'Decrypt',
    time: '1 hour ago',
    readMins: 5,
    reads: '24.1k',
    tags: ['Ethereum', 'Layer 2', 'Scaling'],
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 18,
    category: 'Crypto & Web3',
    title: 'Decentralized (.kt) Domain Registrations Pass 5 Million',
    summary: 'Human-readable handles replace long wallet addresses across multiple chains.',
    body: [
      'Sending crypto is now closer to sending a message: a .kt handle resolves to wallet addresses on Ethereum, Solana and Bitcoin from a single lookup.',
      'Address-poisoning attacks — where a scammer registers a lookalike address — become far harder when the human-facing identifier is a short readable name with on-chain ownership.',
      'Renewal is annual, and lapsed names enter a 90-day grace period before returning to the open market.',
    ],
    author: 'Felix Nordmann',
    source: 'Blockworks',
    time: '2 hours ago',
    readMins: 4,
    reads: '17.6k',
    tags: ['Identity', 'Domains', 'Web3'],
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 19,
    category: 'Crypto & Web3',
    title: 'Passkey Wallets Replace Seed-Phrase Vulnerabilities',
    summary: 'Users recover funds with biometrics and split key shares instead of a written recovery phrase.',
    body: [
      'Self-custody is finally becoming usable. Passkey key shares split across trusted hardware enclaves mean losing a phone no longer means losing an entire portfolio.',
      'The tradeoff is a more complex trust model: users must understand which parties hold which shares, and how many are needed to reconstruct a key.',
      'Security researchers broadly welcome the shift, noting that written seed phrases have been the single largest source of retail crypto loss.',
    ],
    author: 'Grace Whitfield',
    source: 'CoinTelegraph',
    time: '3 hours ago',
    readMins: 6,
    reads: '29.3k',
    tags: ['Passkeys', 'Self-custody', 'Security'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 20,
    category: 'Crypto & Web3',
    title: 'NFT Creator Royalties Automatically Enforced via Smart Contracts',
    summary: 'Digital artists receive secondary-sale royalties directly in their connected chat wallet.',
    body: [
      'Updated contract standards give creators enforceable resale royalties rather than a marketplace-by-marketplace courtesy.',
      'Painters and musicians receive their share in real time as a sale settles, with the split visible on-chain to both parties.',
      'Marketplaces that decline to honour the standard are increasingly filtered out of aggregator listings.',
    ],
    author: 'Isabel Moreau',
    source: 'NFT Now',
    time: '4 hours ago',
    readMins: 4,
    reads: '12.4k',
    tags: ['NFT', 'Creators', 'Royalties'],
    image: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 21,
    category: 'Crypto & Web3',
    title: 'DeFi Lending Protocols Integrate Real-Time Interest Payouts',
    summary: 'Stablecoin depositors see yield credited hourly straight into their messenger balance.',
    body: [
      'Decentralised finance yields are now reachable from a messaging wallet, with compounding payouts and public audit trails for every pool.',
      'Advertised APY figures move with utilisation; the hourly payout makes that variability visible rather than hiding it behind a monthly average.',
      'Deposits carry smart-contract risk and are not covered by deposit insurance — a warning the interface now shows before the first transfer.',
    ],
    author: 'Ayesha Khan',
    source: 'DefiLlama News',
    time: '5 hours ago',
    readMins: 5,
    reads: '20.7k',
    tags: ['DeFi', 'Yield', 'Stablecoins'],
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 22,
    category: 'Crypto & Web3',
    title: 'Cross-Chain Token Swaps Execute in Under Three Seconds',
    summary: 'Swap SOL, ETH and BTC across independent chains with automated routing.',
    body: [
      'Multi-chain liquidity aggregators built into KT Wallet route each swap across 12 networks and surface the quoted execution price before confirmation.',
      'Routing is quote-first: the interface shows the worst-case fill alongside the expected one, so a user can judge slippage rather than discover it.',
      'Bridge risk remains the dominant hazard in cross-chain transfers, and the wallet labels which bridge each route depends on.',
    ],
    author: 'Jonas Weber',
    source: 'The Block',
    time: '6 hours ago',
    readMins: 4,
    reads: '16.1k',
    tags: ['Swaps', 'Cross-chain', 'Liquidity'],
    image: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=800&q=80',
  },

  // --------------------------------------------------------- GLOBAL HEADLINES
  {
    id: 23,
    category: 'Global Headlines',
    title: 'Quantum Communication Links Tested Across Two Continents',
    summary: 'Researchers demonstrate quantum key distribution designed for next-generation encryption.',
    body: [
      'Scientists have successfully tested intercontinental quantum key distribution intended to protect messaging networks against future quantum decryption.',
      'The link ran over a combination of satellite and fibre segments, with key material stitched together at trusted relay nodes.',
      'Commercial deployment remains years away; the immediate value is validating the error-correction stack at continental distance.',
    ],
    author: 'Elena Vasquez',
    source: 'Reuters',
    time: '15 mins ago',
    readMins: 6,
    reads: '26.1k',
    tags: ['Quantum', 'Research', 'Encryption'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 24,
    category: 'Global Headlines',
    title: 'Telecommunication Union Adopts Universal E2EE Standard',
    summary: 'Global regulators mandate end-to-end encryption for consumer messaging services.',
    body: [
      'In a landmark decision for digital rights, the ITU has designated Signal-grade end-to-end encryption as the baseline security standard for consumer communication platforms.',
      'Member states have a three-year transition window, with annual conformance reporting in the interim.',
      'Several national regulators have signalled they will exceed the baseline by also mandating metadata minimisation.',
    ],
    author: 'Claire Dubois',
    source: 'BBC World News',
    time: '1 hour ago',
    readMins: 5,
    reads: '42.0k',
    tags: ['Regulation', 'Encryption', 'Policy'],
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 25,
    category: 'Global Headlines',
    title: 'Digital Sovereignty Summit Concludes With Privacy Pact',
    summary: 'Fifty nations sign an agreement prohibiting mandated backdoors in messaging apps.',
    body: [
      'Leaders from 50 nations ratified the International Digital Privacy Pact, ruling out mandatory cryptographic backdoors in consumer software.',
      'The pact is political rather than binding, but signatories commit to publishing an annual transparency report on lawful-access requests.',
      'Civil liberties groups called the text a strong floor while cautioning that enforcement mechanisms are thin.',
    ],
    author: 'Tom Rivera',
    source: 'Associated Press',
    time: '2 hours ago',
    readMins: 5,
    reads: '35.8k',
    tags: ['Privacy', 'Diplomacy', 'Rights'],
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 26,
    category: 'Global Headlines',
    title: 'Transatlantic Optical Cable System Completed',
    summary: 'Subsea fibre expands intercontinental bandwidth by 400 terabits per second.',
    body: [
      'The completed transatlantic line cuts round-trip latency between Europe and North America to under 28 milliseconds.',
      'Lower latency is most noticeable on live voice and video, where every 10ms shaved reduces the awkward overlap in natural conversation.',
      'Redundancy matters as much as speed: the new route diversifies away from a corridor that carried an outsized share of traffic.',
    ],
    author: 'Marcus Bell',
    source: 'CNN International',
    time: '3 hours ago',
    readMins: 4,
    reads: '18.9k',
    tags: ['Infrastructure', 'Networks', 'Subsea'],
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 27,
    category: 'Global Headlines',
    title: 'Disaster Relief Coordination Powered by Offline Mesh Messaging',
    summary: 'Responders relay SOS locations without cellular coverage using Bluetooth mesh.',
    body: [
      'During hurricane rescue operations, teams deployed peer-to-peer offline mesh networks so trapped survivors could broadcast GPS coordinates to nearby squads.',
      'Each handset acts as a relay, so coverage grows with the number of people in the area rather than depending on surviving infrastructure.',
      'Battery discipline is the limiting factor; the relief protocol drops to a low-power beacon mode below 15% charge.',
    ],
    author: 'Meera Joshi',
    source: 'The Guardian',
    time: '4 hours ago',
    readMins: 6,
    reads: '21.3k',
    tags: ['Mesh', 'Emergency', 'Offline'],
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 28,
    category: 'Global Headlines',
    title: 'Translation Earbuds Connect a Multilingual Diplomatic Delegation',
    summary: 'Delegates converse across 12 languages with near-zero perceptible delay.',
    body: [
      'At a UN cultural exchange, delegates wore low-latency neural translation earbuds, allowing multi-language conversation with natural cadence and preserved tone.',
      'Interpreters remained in the room for anything binding — the devices handled corridor conversation, not treaty language.',
      'Latency, not accuracy, proved the hard problem: a 400ms delay is enough to break the rhythm of a live exchange.',
    ],
    author: 'Lena Fischer',
    source: 'Al Jazeera',
    time: '5 hours ago',
    readMins: 4,
    reads: '15.7k',
    tags: ['Translation', 'Hardware', 'Diplomacy'],
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------- SCIENCE & CLIMATE
  {
    id: 29,
    category: 'Science & Climate',
    title: 'Fusion Reactor Exceeds Net Energy Gain Milestone',
    summary: 'Physicists sustain 100 megawatts of clean plasma output for 12 continuous hours.',
    body: [
      'Fusion scientists sustained a controlled thermonuclear plasma producing 120% net positive energy output, a first at this duration.',
      'The result measures energy out against energy injected into the plasma; whole-plant efficiency, which includes the magnets and cooling, remains the harder target.',
      'Even so, twelve hours of stable confinement answers a long-standing question about whether the regime is achievable outside brief pulses.',
    ],
    author: 'Hiroshi Tanaka',
    source: 'Nature Energy',
    time: '1 hour ago',
    readMins: 7,
    reads: '54.2k',
    tags: ['Fusion', 'Energy', 'Climate'],
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 30,
    category: 'Science & Climate',
    title: 'Webb Telescope Captures Atmosphere Spectrum of an Earth-Like Exoplanet',
    summary: 'Spectroscopy reveals water vapour and candidate biosignature gases 40 light-years away.',
    body: [
      'Astronomers inspecting exoplanet K2-18b detected atmospheric water vapour, carbon dioxide and a dimethyl sulfide signature.',
      'On Earth, dimethyl sulfide is produced almost entirely by marine life, which is why the detection drew immediate attention.',
      'The team stresses the signal sits near the noise floor and needs independent confirmation before anyone draws conclusions about habitability.',
    ],
    author: 'Elena Vasquez',
    source: 'NASA Science',
    time: '2 hours ago',
    readMins: 6,
    reads: '48.9k',
    tags: ['Astronomy', 'Exoplanets', 'Webb'],
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 31,
    category: 'Science & Climate',
    title: 'Perovskite Tandem Cells Smash Solar Efficiency Records',
    summary: 'Commercial panels reach 33.9% conversion efficiency in outdoor field tests.',
    body: [
      'Perovskite-silicon tandem cells generate roughly 40% more electricity per square metre than conventional silicon panels.',
      'Field testing matters here: perovskites historically degraded quickly under real humidity and UV exposure, so outdoor durability data is the headline result.',
      'Manufacturers are targeting pilot production lines within 18 months.',
    ],
    author: 'Sofia Almeida',
    source: 'Scientific American',
    time: '3 hours ago',
    readMins: 5,
    reads: '19.4k',
    tags: ['Solar', 'Materials', 'Energy'],
    image: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 32,
    category: 'Science & Climate',
    title: 'Direct Air Capture Plant Begins Removing 1M Tons of CO₂ a Year',
    summary: 'A geothermal-powered facility mineralises captured carbon into basalt rock.',
    body: [
      'The largest direct air capture facility yet has begun commercial operation, drawing CO₂ from ambient air and locking it into underground stone.',
      'Mineralisation is effectively permanent, which distinguishes it from storage approaches that require indefinite monitoring.',
      'At current cost per tonne, capture remains far more expensive than emission avoidance — the operators frame it as a complement, not a substitute.',
    ],
    author: 'Daniel Okoye',
    source: 'National Geographic',
    time: '4 hours ago',
    readMins: 6,
    reads: '23.1k',
    tags: ['Carbon Capture', 'Climate', 'Geothermal'],
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 33,
    category: 'Science & Climate',
    title: 'AI mRNA Platform Designs Custom Cancer Treatments in 48 Hours',
    summary: 'Personalised immunotherapy enters Phase 3 trials across 50 medical centres.',
    body: [
      'Researchers use generative models to sequence tumour DNA and design personalised mRNA vaccines that train the immune system against a specific cancer.',
      'The 48-hour figure covers design; manufacturing and quality release add a further two to three weeks in current trial logistics.',
      'Phase 3 enrolment is the first test at a scale where rare adverse events become visible.',
    ],
    author: 'Nina Kaur',
    source: 'The Lancet',
    time: '5 hours ago',
    readMins: 7,
    reads: '37.8k',
    tags: ['Biotech', 'Oncology', 'mRNA'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 34,
    category: 'Science & Climate',
    title: 'Ocean Reforestation Restores 10,000 Hectares of Kelp Forest',
    summary: 'Autonomous underwater planters re-seed marine biodiversity hotspots.',
    body: [
      'Conservationists deploying autonomous submarine drones have restored thousands of hectares of coastal giant kelp, providing sanctuary for endangered fish species.',
      'Kelp grows fast enough that recovery is measurable within a single season, making it an unusually legible restoration target.',
      'Long-term survival depends on controlling urchin populations, which is where the programme now focuses.',
    ],
    author: 'Isabel Moreau',
    source: 'Ocean Graphic',
    time: '6 hours ago',
    readMins: 5,
    reads: '14.0k',
    tags: ['Oceans', 'Biodiversity', 'Restoration'],
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  },

  // ------------------------------------------------------------ ENTERTAINMENT
  {
    id: 35,
    category: 'Entertainment',
    title: 'Interactive VR Cinema Premieres Simultaneously in 50 Countries',
    summary: 'Audiences steer the plot in real time using chat polls inside virtual theatres.',
    body: [
      'Viewers watching the sci-fi thriller "Project Continuum" voted on narrative choices from their phones, producing 16 possible endings.',
      'The production shot 40% more footage than a linear film of the same length, which is the practical ceiling on how branchy interactive cinema can get.',
      'Repeat viewing rates were four times the studio average, suggesting the format monetises differently from a traditional release.',
    ],
    author: 'Marcus Bell',
    source: 'Hollywood Reporter',
    time: '1 hour ago',
    readMins: 5,
    reads: '29.5k',
    tags: ['VR', 'Film', 'Interactive'],
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hot: true,
  },
  {
    id: 36,
    category: 'Entertainment',
    title: 'AI Music Co-Producers Top Global Streaming Charts',
    summary: 'Human-AI collaborations pass one billion streams worldwide.',
    body: [
      'Artists using generative composition assistants are charting consistently, with "Digital Horizon" holding the global number-one spot for a third week.',
      'Credit conventions are still unsettled: some labels list the model as a tool, others as a co-writer, with real royalty consequences either way.',
      'Streaming platforms have begun requiring disclosure of substantial AI contribution at upload.',
    ],
    author: 'Ayesha Khan',
    source: 'Billboard',
    time: '2 hours ago',
    readMins: 4,
    reads: '32.1k',
    tags: ['Music', 'AI', 'Streaming'],
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 37,
    category: 'Entertainment',
    title: 'Esports World Cup Final Draws Record 85 Million Concurrent Viewers',
    summary: 'Fans stream multi-angle 4K feeds inside official gaming channels.',
    body: [
      'Championship viewership shattered previous records, with 85 million concurrent viewers on high-bitrate streams and in-chat prediction games running alongside.',
      'Multi-angle feeds let viewers follow a single player rather than the broadcast director’s cut, which drove significantly longer session times.',
      'Prize pool growth continues to outpace traditional sports at the top end while remaining thin below the elite tier.',
    ],
    author: 'Tom Rivera',
    source: 'IGN',
    time: '3 hours ago',
    readMins: 4,
    reads: '41.7k',
    tags: ['Esports', 'Streaming', 'Gaming'],
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 38,
    category: 'Entertainment',
    title: 'Indie Developers Raise $50M Through Community Chat Crowdfunding',
    summary: 'Backers play browser-playable alpha demos without leaving the conversation.',
    body: [
      'Community-driven game development is thriving. Sharing instantly playable demos in creator channels helped indie studio PixelCraft raise $50M without a publisher.',
      'The playable-demo-in-thread pattern converts far better than a trailer, because backers evaluate feel rather than promises.',
      'Studios warn that community funding brings community expectations — scope creep is the most-cited post-campaign risk.',
    ],
    author: 'Felix Nordmann',
    source: 'Polygon',
    time: '4 hours ago',
    readMins: 5,
    reads: '16.8k',
    tags: ['Indie Games', 'Crowdfunding', 'Community'],
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 39,
    category: 'Entertainment',
    title: 'Holographic Concert Tour Sells Out 20 Stadiums in Five Minutes',
    summary: 'Photorealistic avatars perform alongside live symphony orchestras.',
    body: [
      'Laser projection systems place life-sized photorealistic avatars on stage, synchronised with live symphonic musicians.',
      'Estate approval and likeness rights are negotiated per artist, and several estates have publicly declined.',
      'Audiences describe the effect as convincing at distance and noticeably artificial in the front rows.',
    ],
    author: 'Isabel Moreau',
    source: 'Rolling Stone',
    time: '5 hours ago',
    readMins: 4,
    reads: '28.4k',
    tags: ['Live Music', 'Holograms', 'Touring'],
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 40,
    category: 'Entertainment',
    title: 'AI Scriptwriting Assistants Adopted by 80% of Major Writers Rooms',
    summary: 'Writers use conversational tools to explore dialogue variations and character arcs.',
    body: [
      'Writers rooms report faster scene outlining, using assistants to test plot twists and dialogue cadence before committing to a draft.',
      'Union agreements set the boundary: assistants may generate material for consideration, but credited writing must originate with a person.',
      'Showrunners describe the tool as a brainstorming partner that is useful precisely because its suggestions are easy to reject.',
    ],
    author: 'Lena Fischer',
    source: 'Variety',
    time: '6 hours ago',
    readMins: 5,
    reads: '20.9k',
    tags: ['Television', 'Writing', 'AI'],
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=800&q=80',
  },
]

export const newsSources = [
  { name: 'Reuters', focus: 'Wire & world', articles: 812, verified: true },
  { name: 'Bloomberg', focus: 'Markets & business', articles: 640, verified: true },
  { name: 'TechCrunch', focus: 'Startups & product', articles: 574, verified: true },
  { name: 'The Verge', focus: 'Consumer tech', articles: 498, verified: true },
  { name: 'CoinDesk', focus: 'Digital assets', articles: 455, verified: true },
  { name: 'Nature', focus: 'Peer-reviewed science', articles: 310, verified: true },
  { name: 'BBC World', focus: 'Global affairs', articles: 726, verified: true },
  { name: 'Financial Times', focus: 'Policy & economics', articles: 389, verified: true },
  { name: 'MIT Tech Review', focus: 'Deep tech', articles: 244, verified: true },
  { name: 'The Guardian', focus: 'Investigations', articles: 402, verified: true },
  { name: 'Associated Press', focus: 'Breaking wire', articles: 905, verified: true },
  { name: 'Variety', focus: 'Media & culture', articles: 268, verified: true },
]

export const followTopics = [
  'Artificial Intelligence',
  'Cybersecurity',
  'Startups',
  'Indian Markets',
  'Crypto',
  'Climate',
  'Space',
  'Health',
  'Gaming',
  'Elections',
  'Sports',
  'Design',
  'Semiconductors',
  'Electric Vehicles',
  'Open Source',
  'Renewables',
]

export const digestSchedule = [
  {
    slot: 'Morning brief',
    time: '07:00',
    desc: 'Overnight headlines and the three stories shaping your day, in about three minutes.',
  },
  { slot: 'Market open', time: '09:15', desc: 'Index levels, pre-open movers and the one number that matters today.' },
  { slot: 'Midday catch-up', time: '13:30', desc: 'What broke since breakfast, filtered to the topics you follow.' },
  { slot: 'Evening wrap', time: '20:00', desc: 'A calmer read: analysis, long reads and tomorrow’s calendar.' },
]

export const factChecks = [
  {
    claim: '“New encryption law bans private messaging outright.”',
    verdict: 'Misleading',
    tone: 'warning',
    detail:
      'The draft text regulates lawful-access reporting. It does not prohibit end-to-end encryption, and no clause requires a backdoor.',
  },
  {
    claim: '“Fusion reactor now powers a national grid.”',
    verdict: 'False',
    tone: 'false',
    detail:
      'The reactor achieved net energy gain in a controlled experiment. No fusion plant is currently connected to any grid.',
  },
  {
    claim: '“Satellite messaging works on any phone, anywhere, today.”',
    verdict: 'Partly true',
    tone: 'warning',
    detail: 'Direct-to-cellular is in beta on supported bands and regions. Coverage and device support are both limited.',
  },
  {
    claim: '“In-chat payments settle instantly with zero fees for merchants.”',
    verdict: 'True',
    tone: 'true',
    detail:
      'Peer-to-peer UPI transfers settle in seconds at no cost. Merchant settlement lands next business day with published rates.',
  },
]

export const newsFaqs = [
  {
    q: 'Where do KT News stories come from?',
    a: 'Every article is syndicated from a verified publisher with a signed feed. The publisher name, byline and original timestamp travel with the story, and nothing is rewritten in transit.',
    tag: 'Sourcing',
  },
  {
    q: 'Does reading news reveal my interests to anyone?',
    a: 'No. Ranking runs on-device against a local interest profile. The server sends a broad candidate set and never learns which stories you actually opened.',
    tag: 'Privacy',
  },
  {
    q: 'How is the AI audio digest generated?',
    a: 'KT AI Co-Pilot summarises the day’s verified stories into a short script, then reads it with a neural voice. Each segment links back to the full article so you can check the source.',
    tag: 'AI',
  },
  {
    q: 'Can I read articles offline?',
    a: 'Yes. Bookmarked stories are cached in your encrypted vault with their images, and stay readable on flights or in low-coverage areas.',
    tag: 'Offline',
  },
  {
    q: 'How does fact-checking work?',
    a: 'Claims circulating widely in channels are routed to partner fact-checking organisations. Their verdict is attached to the claim wherever it is forwarded, along with the reasoning.',
    tag: 'Trust',
  },
  {
    q: 'Can I turn off a topic I never want to see?',
    a: 'Yes. Mute any topic, publisher or keyword from the feed menu. Muted items are filtered before ranking, so they never surface — not even in trending.',
    tag: 'Control',
  },
  {
    q: 'Is there a limit to how many topics I can follow?',
    a: 'You can follow up to 40 topics and 100 publishers. Beyond that the feed tends to lose focus, so the interface nudges you to prune rather than silently degrading.',
    tag: 'Limits',
  },
  {
    q: 'How do I share a story into a chat?',
    a: 'Tap share on any card to send a rich preview into a conversation. The recipient sees the headline, source and a read-time estimate without leaving the thread.',
    tag: 'Sharing',
  },
  {
    q: 'Do publishers pay to appear in the feed?',
    a: 'No. Placement is never sold. Sponsored items, when they appear, carry a permanent label and are excluded from trending and from the audio digest.',
    tag: 'Editorial',
  },
  {
    q: 'What languages are supported?',
    a: 'The feed reads in 50+ languages, and any article can be translated inline while preserving the original text one tap away.',
    tag: 'Languages',
  },
]

export const newsFeatures = [
  {
    title: 'Verified publishers only',
    desc: 'Every feed is signed at the source. If a signature fails, the story never reaches you — no exceptions for speed.',
  },
  {
    title: 'On-device ranking',
    desc: 'Your interest profile stays on your phone. The server sends candidates; your device decides the order.',
  },
  {
    title: 'Three-minute audio brief',
    desc: 'A narrated digest of the day’s verified stories, generated fresh four times daily and always source-linked.',
  },
  {
    title: 'Instant translation',
    desc: 'Read any story in 50+ languages with the original text one tap away for anything you want to double-check.',
  },
  {
    title: 'Offline reading vault',
    desc: 'Bookmarks sync encrypted across devices and stay readable with images when you have no signal.',
  },
  {
    title: 'Claim-level fact checks',
    desc: 'Verdicts from partner organisations attach to the claim itself, so they follow it wherever it gets forwarded.',
  },
  {
    title: 'Share into any chat',
    desc: 'Send a rich preview into a conversation with headline, source and read time, without leaving the thread.',
  },
  {
    title: 'Mute anything',
    desc: 'Silence a topic, keyword or publisher permanently. Muted items are filtered before ranking ever runs.',
  },
  {
    title: 'Zero tracking pixels',
    desc: 'Articles render in a sanitised reader. Third-party trackers and auto-playing scripts are stripped out.',
  },
]

export const newsSteps = [
  { title: 'Pick your topics', desc: 'Follow the subjects and publishers you care about. Everything else stays out of the way.' },
  { title: 'Feed builds on-device', desc: 'Ranking happens on your phone against a local profile, so your reading stays private.' },
  { title: 'Read, listen or translate', desc: 'Open the full story, play the audio brief, or read it in your own language.' },
  { title: 'Save and share', desc: 'Bookmark to your encrypted vault or forward a rich preview into any conversation.' },
]

export const newsTestimonials = [
  {
    quote:
      'I replaced four news apps with this. The morning audio brief runs while I commute and I arrive already caught up.',
    name: 'Ananya Iyer',
    role: 'Product manager, Bengaluru',
  },
  {
    quote:
      'The fact-check labels are the reason I trust forwards in my family group again. The verdict travels with the claim.',
    name: 'Rahul Bose',
    role: 'Teacher, Pune',
  },
  {
    quote: 'On-device ranking sold me. My reading history is genuinely nobody else’s business.',
    name: 'Marta Silva',
    role: 'Security engineer, Lisbon',
  },
  {
    quote: 'Offline caching is underrated. I read the whole evening wrap on a flight with no wifi.',
    name: 'Kenji Sato',
    role: 'Consultant, Osaka',
  },
  {
    quote: 'Muting keywords actually works. Election season was genuinely bearable this year.',
    name: 'Fatima Zahra',
    role: 'Designer, Casablanca',
  },
  {
    quote: 'I share three stories a day into team channels. The preview card does all the explaining for me.',
    name: 'Oliver Grant',
    role: 'Analyst, Manchester',
  },
]
