import React from 'react'
import {
  LayoutDashboard,
  FileText,
  Tags,
  Hash,
  HelpCircle,
  MessageSquare,
  Trophy,
  Package,
  Layers,
  Compass,
  Link2,
  Globe,
  Image,
  Mail,
  Inbox,
  ThumbsUp,
  LineChart,
  UserCheck,
  ShieldCheck,
  History,
  Settings,
  User,
  Search,
  Bell,
  ChevronDown,
  Plus,
  ArrowUpRight,
  ArrowDownRight,
  TrendingUp,
  Download,
  CheckCircle2,
  FileEdit,
  Clock,
  Sparkles,
  RefreshCw,
  MoreVertical,
  LogOut,
  ExternalLink,
} from 'lucide-react'

const ICON_MAP = {
  // Navigation & General
  dashboard: LayoutDashboard,
  blogs: FileText,
  categories: Tags,
  tags: Hash,
  help: HelpCircle,
  faqs: MessageSquare,
  success: Trophy,
  releases: Package,
  content: Layers,
  navigation: Compass,
  footer: Link2,
  locales: Globe,
  media: Image,
  subscribers: Mail,
  contact: Inbox,
  feedback: ThumbsUp,
  analytics: LineChart,
  admins: UserCheck,
  roles: ShieldCheck,
  audit: History,
  emailSettings: Settings,
  profile: User,
  
  // Quick UI Icons
  search: Search,
  bell: Bell,
  chevronDown: ChevronDown,
  plus: Plus,
  upTrend: ArrowUpRight,
  downTrend: ArrowDownRight,
  trending: TrendingUp,
  download: Download,
  check: CheckCircle2,
  edit: FileEdit,
  clock: Clock,
  sparkles: Sparkles,
  refresh: RefreshCw,
  more: MoreVertical,
  logout: LogOut,
  external: ExternalLink,
}

export function Icon({ name, size = 18, className = '', color, ...props }) {
  const Component = ICON_MAP[name] || LayoutDashboard
  return <Component size={size} className={className} color={color} {...props} />
}
