// ---------------------------------------------------------------------------
// KT Marketplace — page content.
// Sample catalogue used to demonstrate the in-chat shopping interface.
// ---------------------------------------------------------------------------

export const productCategories = ['All', 'Electronics', 'Gadgets', 'Home', 'Fashion', 'Beauty', 'Sports', 'Grocery']

export const products = [
  // ------------------------------------------------------------- ELECTRONICS
  {
    id: 1,
    name: 'Wireless Noise-Cancelling Headphones',
    seller: 'Acme Electronics',
    price: 4999,
    mrp: 7999,
    rating: 4.9,
    reviews: 1240,
    category: 'Electronics',
    tag: 'Flash sale',
    delivery: '2-day delivery',
    stock: 18,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    desc: 'Hybrid active noise cancellation with 30 hours of playback and Bluetooth 5.3 multipoint pairing across two devices.',
    features: ['30h battery', 'Hybrid ANC', 'Multipoint pairing', 'USB-C fast charge'],
  },
  {
    id: 2,
    name: 'Ultra HD 4K Streaming Webcam',
    seller: 'VisionTech',
    price: 3499,
    mrp: 5499,
    rating: 4.8,
    reviews: 890,
    category: 'Electronics',
    tag: 'Popular',
    delivery: '2-day delivery',
    stock: 34,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    desc: 'Sharp 4K capture with dual noise-cancelling microphones and automatic low-light correction for evening calls.',
    features: ['4K 30fps', 'Dual mics', 'Auto low-light', 'Privacy shutter'],
  },
  {
    id: 3,
    name: 'Portable Waterproof Bluetooth Speaker',
    seller: 'SoundWave Store',
    price: 1999,
    mrp: 3299,
    rating: 4.7,
    reviews: 640,
    category: 'Electronics',
    tag: 'Trending',
    delivery: 'Next-day delivery',
    stock: 52,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80',
    desc: 'IPX7 waterproof housing with a passive bass radiator, 15 hours of playback and a rugged shockproof shell.',
    features: ['IPX7 rated', '15h playback', 'Bass radiator', 'Stereo pairing'],
  },
  {
    id: 4,
    name: 'Mechanical RGB Gaming Keyboard',
    seller: 'HyperKey Pro',
    price: 3999,
    mrp: 5999,
    rating: 4.9,
    reviews: 1820,
    category: 'Electronics',
    tag: 'Gamer choice',
    delivery: '2-day delivery',
    stock: 27,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=600&q=80',
    desc: 'Hot-swappable tactile switches, per-key RGB lighting and a machined aluminium chassis that does not flex.',
    features: ['Hot-swap switches', 'Per-key RGB', 'Aluminium body', 'Detachable cable'],
  },
  {
    id: 5,
    name: 'Studio Condenser Microphone',
    seller: 'AudioCraft',
    price: 5499,
    mrp: 8499,
    rating: 4.8,
    reviews: 950,
    category: 'Electronics',
    tag: 'Pro studio',
    delivery: '3-day delivery',
    stock: 12,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    desc: 'Broadcast-grade 192kHz/24-bit sampling with a cardioid pickup pattern and zero-latency headphone monitoring.',
    features: ['192kHz/24-bit', 'Cardioid pattern', 'Zero-latency monitor', 'Shock mount included'],
  },
  {
    id: 6,
    name: '27" QHD Monitor with USB-C',
    seller: 'VisionTech',
    price: 18499,
    mrp: 24999,
    rating: 4.7,
    reviews: 412,
    category: 'Electronics',
    tag: 'Work setup',
    delivery: '4-day delivery',
    stock: 9,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    desc: 'A 27-inch 1440p IPS panel with 90W USB-C power delivery, so one cable handles video, data and charging.',
    features: ['1440p IPS', '90W USB-C PD', '99% sRGB', 'Height adjustable'],
  },

  // ----------------------------------------------------------------- GADGETS
  {
    id: 7,
    name: 'Smart Fitness Tracker Watch',
    seller: 'FitTech Store',
    price: 2499,
    mrp: 4199,
    rating: 4.8,
    reviews: 2150,
    category: 'Gadgets',
    tag: 'Best seller',
    delivery: 'Next-day delivery',
    stock: 74,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    desc: 'Heart rate, SpO₂ and sleep tracking across 20+ sport modes, with ten days of battery on a single charge.',
    features: ['10-day battery', 'SpO₂ sensor', '20+ sport modes', '5ATM water resistant'],
  },
  {
    id: 8,
    name: 'Ergonomic Vertical Wireless Mouse',
    seller: 'DeskLab Pro',
    price: 1299,
    mrp: 2199,
    rating: 4.6,
    reviews: 410,
    category: 'Gadgets',
    tag: 'New',
    delivery: '2-day delivery',
    stock: 61,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    desc: 'A 57° vertical posture that takes the twist out of your forearm, with silent clicks and dual-mode pairing.',
    features: ['57° vertical', 'Silent clicks', '2.4G + Bluetooth', 'Rechargeable'],
  },
  {
    id: 9,
    name: '20,000mAh Fast-Charge Power Bank',
    seller: 'VoltGear',
    price: 1799,
    mrp: 2999,
    rating: 4.7,
    reviews: 1580,
    category: 'Gadgets',
    tag: 'Travel pick',
    delivery: 'Next-day delivery',
    stock: 96,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&q=80',
    desc: '65W USB-C output charges a laptop, with a digital readout so you always know exactly what is left.',
    features: ['65W USB-C PD', 'Digital readout', 'Charges laptops', 'Airline safe'],
  },
  {
    id: 10,
    name: 'Wireless Earbuds with ANC',
    seller: 'SoundWave Store',
    price: 2999,
    mrp: 4999,
    rating: 4.6,
    reviews: 3240,
    category: 'Gadgets',
    tag: 'Flash sale',
    delivery: 'Next-day delivery',
    stock: 43,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    desc: 'Compact buds with adaptive noise cancellation, a transparency mode and 28 hours total with the case.',
    features: ['Adaptive ANC', 'Transparency mode', '28h with case', 'Wireless charging'],
  },
  {
    id: 11,
    name: 'Foldable Laptop Stand — Aluminium',
    seller: 'DeskLab Pro',
    price: 1499,
    mrp: 2499,
    rating: 4.8,
    reviews: 720,
    category: 'Gadgets',
    tag: 'Ergonomic',
    delivery: '2-day delivery',
    stock: 88,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    desc: 'Six height positions, a fold-flat hinge for travel and silicone pads that keep the machine from sliding.',
    features: ['6 height stops', 'Folds flat', 'Holds up to 17"', 'Silicone grips'],
  },
  {
    id: 12,
    name: 'Smart Video Doorbell',
    seller: 'HomeSecure',
    price: 5999,
    mrp: 8999,
    rating: 4.5,
    reviews: 380,
    category: 'Gadgets',
    tag: 'Smart home',
    delivery: '3-day delivery',
    stock: 22,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    desc: 'Two-way audio, 1080p night vision and motion alerts that land straight in your KT chat rather than a separate app.',
    features: ['1080p night vision', 'Two-way audio', 'Chat alerts', 'Local storage option'],
  },

  // -------------------------------------------------------------------- HOME
  {
    id: 13,
    name: 'Ceramic Pour-Over Coffee Set',
    seller: 'Brew & Co.',
    price: 2199,
    mrp: 3299,
    rating: 4.9,
    reviews: 540,
    category: 'Home',
    tag: 'Editor’s pick',
    delivery: '3-day delivery',
    stock: 31,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    desc: 'A hand-glazed ceramic dripper, 600ml server and reusable steel filter — everything for a proper morning cup.',
    features: ['Hand-glazed ceramic', '600ml server', 'Reusable filter', 'Dishwasher safe'],
  },
  {
    id: 14,
    name: 'Air Purifier with HEPA H13',
    seller: 'PureLiving',
    price: 8999,
    mrp: 13999,
    rating: 4.7,
    reviews: 1120,
    category: 'Home',
    tag: 'Trending',
    delivery: '4-day delivery',
    stock: 16,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=600&q=80',
    desc: 'True HEPA H13 filtration rated for a 400 sq ft room, with a real-time PM2.5 readout and a 24dB night mode.',
    features: ['HEPA H13', '400 sq ft', 'PM2.5 display', '24dB night mode'],
  },
  {
    id: 15,
    name: 'Weighted Blanket — 7kg Cotton',
    seller: 'SleepWell Home',
    price: 3499,
    mrp: 5999,
    rating: 4.6,
    reviews: 860,
    category: 'Home',
    tag: 'Bestseller',
    delivery: '3-day delivery',
    stock: 40,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    desc: 'Breathable cotton with evenly distributed glass beads and a removable, machine-washable cover.',
    features: ['7kg weight', 'Breathable cotton', 'Removable cover', 'Machine washable'],
  },
  {
    id: 16,
    name: 'Indoor Plant Trio with Pots',
    seller: 'GreenNest',
    price: 1299,
    mrp: 1999,
    rating: 4.8,
    reviews: 1430,
    category: 'Home',
    tag: 'Popular',
    delivery: '2-day delivery',
    stock: 65,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80',
    desc: 'Snake plant, pothos and ZZ plant in matte ceramic pots — the three hardest houseplants to kill.',
    features: ['3 live plants', 'Ceramic pots', 'Low light tolerant', 'Care card included'],
  },
  {
    id: 17,
    name: 'Cast Iron Skillet — 26cm',
    seller: 'Hearth Kitchen',
    price: 1899,
    mrp: 2899,
    rating: 4.9,
    reviews: 980,
    category: 'Home',
    tag: 'Kitchen',
    delivery: '3-day delivery',
    stock: 48,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    desc: 'Pre-seasoned cast iron that works on induction, gas and open flame, and improves every time you cook on it.',
    features: ['Pre-seasoned', 'Induction ready', 'Oven safe 260°C', 'Lifetime piece'],
  },
  {
    id: 18,
    name: 'Smart LED Strip — 5m',
    seller: 'GlowHaus',
    price: 999,
    mrp: 1799,
    rating: 4.4,
    reviews: 2260,
    category: 'Home',
    tag: 'Flash sale',
    delivery: 'Next-day delivery',
    stock: 120,
    image: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=600&q=80',
    desc: 'Sixteen million colours, music-reactive modes and scheduling from chat — no hub or bridge required.',
    features: ['16M colours', 'Music sync', 'App scheduling', 'No hub needed'],
  },

  // ----------------------------------------------------------------- FASHION
  {
    id: 19,
    name: 'Merino Wool Crew Sweater',
    seller: 'North Thread',
    price: 3299,
    mrp: 5499,
    rating: 4.7,
    reviews: 640,
    category: 'Fashion',
    tag: 'Winter',
    delivery: '3-day delivery',
    stock: 37,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80',
    desc: 'Fine-gauge merino that regulates temperature and resists odour, so it survives three wears between washes.',
    features: ['100% merino', 'Temperature regulating', 'Odour resistant', 'Machine washable'],
  },
  {
    id: 20,
    name: 'Leather Minimalist Wallet',
    seller: 'Craft & Hide',
    price: 1699,
    mrp: 2799,
    rating: 4.8,
    reviews: 1310,
    category: 'Fashion',
    tag: 'Gift pick',
    delivery: '2-day delivery',
    stock: 82,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    desc: 'Full-grain vegetable-tanned leather with RFID blocking and a slim profile that holds six cards comfortably.',
    features: ['Full-grain leather', 'RFID blocking', 'Holds 6 cards', 'Ages beautifully'],
  },
  {
    id: 21,
    name: 'Everyday Canvas Backpack — 22L',
    seller: 'North Thread',
    price: 2499,
    mrp: 3999,
    rating: 4.6,
    reviews: 890,
    category: 'Fashion',
    tag: 'Commuter',
    delivery: '2-day delivery',
    stock: 54,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    desc: 'Water-resistant waxed canvas, a padded 15-inch laptop sleeve and a luggage pass-through for travel days.',
    features: ['22L capacity', 'Waxed canvas', '15" laptop sleeve', 'Luggage strap'],
  },
  {
    id: 22,
    name: 'Polarised Aviator Sunglasses',
    seller: 'Solstice Optics',
    price: 1899,
    mrp: 3499,
    rating: 4.5,
    reviews: 720,
    category: 'Fashion',
    tag: 'Summer',
    delivery: 'Next-day delivery',
    stock: 66,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
    desc: 'Polarised lenses with full UV400 protection in a lightweight titanium frame and spring-loaded hinges.',
    features: ['Polarised', 'UV400', 'Titanium frame', 'Hard case included'],
  },
  {
    id: 23,
    name: 'Running Shoes — Neutral Cushion',
    seller: 'StrideLab',
    price: 4499,
    mrp: 6999,
    rating: 4.7,
    reviews: 1960,
    category: 'Fashion',
    tag: 'Bestseller',
    delivery: '2-day delivery',
    stock: 29,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    desc: 'A responsive foam midsole tuned for daily mileage, with a breathable engineered mesh upper.',
    features: ['Neutral support', 'Responsive foam', 'Engineered mesh', '260g per shoe'],
  },
  {
    id: 24,
    name: 'Cotton Oxford Shirt',
    seller: 'Craft & Hide',
    price: 1799,
    mrp: 2999,
    rating: 4.6,
    reviews: 480,
    category: 'Fashion',
    tag: 'Everyday',
    delivery: '3-day delivery',
    stock: 71,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
    desc: 'Heavyweight oxford cotton with a soft-roll collar that looks right with or without a jacket.',
    features: ['Oxford cotton', 'Soft-roll collar', 'Pre-shrunk', 'Six colourways'],
  },

  // ------------------------------------------------------------------ BEAUTY
  {
    id: 25,
    name: 'Vitamin C Brightening Serum',
    seller: 'Glow Lab',
    price: 1299,
    mrp: 2199,
    rating: 4.7,
    reviews: 2840,
    category: 'Beauty',
    tag: 'Bestseller',
    delivery: 'Next-day delivery',
    stock: 140,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
    desc: '15% L-ascorbic acid stabilised with ferulic acid, in an amber bottle that keeps it from oxidising early.',
    features: ['15% vitamin C', 'Ferulic acid', 'Amber glass', 'Fragrance free'],
  },
  {
    id: 26,
    name: 'Ceramide Barrier Moisturiser',
    seller: 'Glow Lab',
    price: 999,
    mrp: 1599,
    rating: 4.8,
    reviews: 1920,
    category: 'Beauty',
    tag: 'Dermatologist pick',
    delivery: 'Next-day delivery',
    stock: 165,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    desc: 'Three ceramides plus hyaluronic acid in a non-comedogenic base that layers cleanly under sunscreen.',
    features: ['3 ceramides', 'Non-comedogenic', 'Fragrance free', 'Layers under SPF'],
  },
  {
    id: 27,
    name: 'Mineral Sunscreen SPF 50 PA++++',
    seller: 'SunGuard',
    price: 899,
    mrp: 1399,
    rating: 4.6,
    reviews: 3410,
    category: 'Beauty',
    tag: 'Daily use',
    delivery: 'Next-day delivery',
    stock: 210,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80',
    desc: 'Zinc-oxide based, reef-safe and genuinely white-cast free on medium and deep skin tones.',
    features: ['SPF 50 PA++++', 'No white cast', 'Reef safe', 'Water resistant 80min'],
  },
  {
    id: 28,
    name: 'Argan Hair Repair Oil',
    seller: 'Rooted Beauty',
    price: 749,
    mrp: 1299,
    rating: 4.5,
    reviews: 1080,
    category: 'Beauty',
    tag: 'Flash sale',
    delivery: '2-day delivery',
    stock: 132,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=600&q=80',
    desc: 'Cold-pressed argan with jojoba, light enough for fine hair and effective on split ends.',
    features: ['Cold-pressed argan', 'Lightweight', 'Heat protection', 'Cruelty free'],
  },
  {
    id: 29,
    name: 'Electric Facial Cleansing Brush',
    seller: 'Rooted Beauty',
    price: 2299,
    mrp: 3799,
    rating: 4.4,
    reviews: 520,
    category: 'Beauty',
    tag: 'New',
    delivery: '3-day delivery',
    stock: 44,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=600&q=80',
    desc: 'Silicone sonic bristles with three intensity levels, fully waterproof and 60 days of use per charge.',
    features: ['Sonic silicone', '3 intensities', 'IPX7 waterproof', '60-day battery'],
  },
  {
    id: 30,
    name: 'Matte Liquid Lipstick Set of 4',
    seller: 'Glow Lab',
    price: 1199,
    mrp: 2099,
    rating: 4.6,
    reviews: 1650,
    category: 'Beauty',
    tag: 'Gift pick',
    delivery: 'Next-day delivery',
    stock: 78,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80',
    desc: 'Four transfer-resistant nudes with a comfortable matte finish that does not crack through a full day.',
    features: ['Transfer resistant', '4 shades', 'Vitamin E', '8-hour wear'],
  },

  // ------------------------------------------------------------------ SPORTS
  {
    id: 31,
    name: 'Non-Slip Yoga Mat — 6mm',
    seller: 'ZenFlex',
    price: 1499,
    mrp: 2499,
    rating: 4.8,
    reviews: 1740,
    category: 'Sports',
    tag: 'Bestseller',
    delivery: '2-day delivery',
    stock: 91,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80',
    desc: 'Closed-cell TPE that grips when your hands are wet, with alignment lines printed into the surface.',
    features: ['6mm cushion', 'Closed-cell TPE', 'Alignment lines', 'Carry strap'],
  },
  {
    id: 32,
    name: 'Adjustable Dumbbell Pair — 24kg',
    seller: 'PowerGym',
    price: 8999,
    mrp: 13999,
    rating: 4.7,
    reviews: 620,
    category: 'Sports',
    tag: 'Home gym',
    delivery: '5-day delivery',
    stock: 14,
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80',
    desc: 'Dial from 2kg to 24kg per hand in one second, replacing fifteen pairs of fixed dumbbells.',
    features: ['2–24kg per hand', 'One-second dial', 'Steel plates', 'Compact footprint'],
  },
  {
    id: 33,
    name: 'Resistance Band Set — 5 Levels',
    seller: 'ZenFlex',
    price: 899,
    mrp: 1599,
    rating: 4.6,
    reviews: 2210,
    category: 'Sports',
    tag: 'Flash sale',
    delivery: 'Next-day delivery',
    stock: 178,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80',
    desc: 'Five colour-coded latex bands from extra light to extra heavy, with door anchor and travel pouch.',
    features: ['5 resistance levels', 'Door anchor', 'Travel pouch', 'Natural latex'],
  },
  {
    id: 34,
    name: 'Speed Jump Rope — Ball Bearing',
    seller: 'ProFit Gear',
    price: 449,
    mrp: 799,
    rating: 4.8,
    reviews: 1050,
    category: 'Sports',
    tag: 'Cardio',
    delivery: 'Next-day delivery',
    stock: 240,
    image: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=600&q=80',
    desc: 'A 360° ball-bearing mechanism with adjustable steel cable and memory-foam handles that stay dry.',
    features: ['Ball bearings', 'Adjustable cable', 'Memory foam grips', 'Spare cable included'],
  },
  {
    id: 35,
    name: 'Insulated Steel Water Bottle — 1L',
    seller: 'ProFit Gear',
    price: 1099,
    mrp: 1799,
    rating: 4.9,
    reviews: 3120,
    category: 'Sports',
    tag: 'Popular',
    delivery: 'Next-day delivery',
    stock: 156,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    desc: 'Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12, with a genuinely leak-proof lid.',
    features: ['24h cold / 12h hot', 'Leak-proof lid', '18/8 steel', 'Fits cup holders'],
  },
  {
    id: 36,
    name: 'Cycling Helmet with MIPS',
    seller: 'StrideLab',
    price: 3999,
    mrp: 5999,
    rating: 4.7,
    reviews: 430,
    category: 'Sports',
    tag: 'Safety',
    delivery: '3-day delivery',
    stock: 33,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
    desc: 'MIPS rotational-impact protection with 18 vents and a dial fit system that adjusts one-handed while riding.',
    features: ['MIPS protection', '18 vents', 'Dial fit system', '290g'],
  },

  // ----------------------------------------------------------------- GROCERY
  {
    id: 37,
    name: 'Single-Origin Coffee Beans — 500g',
    seller: 'Brew & Co.',
    price: 799,
    mrp: 1099,
    rating: 4.9,
    reviews: 2480,
    category: 'Grocery',
    tag: 'Subscribe & save',
    delivery: 'Next-day delivery',
    stock: 190,
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=600&q=80',
    desc: 'Chikmagalur arabica roasted to order, with the roast date printed on every bag rather than a best-before.',
    features: ['Roasted to order', 'Single origin', 'Whole bean', 'Roast date printed'],
  },
  {
    id: 38,
    name: 'Cold-Pressed Extra Virgin Olive Oil — 1L',
    seller: 'Pantry Staples',
    price: 1249,
    mrp: 1799,
    rating: 4.7,
    reviews: 940,
    category: 'Grocery',
    tag: 'Kitchen',
    delivery: '2-day delivery',
    stock: 108,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    desc: 'First cold press with an acidity under 0.4%, bottled in dark glass with the harvest date on the label.',
    features: ['<0.4% acidity', 'First cold press', 'Dark glass', 'Harvest dated'],
  },
  {
    id: 39,
    name: 'Raw Forest Honey — 750g',
    seller: 'GreenNest',
    price: 649,
    mrp: 999,
    rating: 4.8,
    reviews: 1370,
    category: 'Grocery',
    tag: 'Trending',
    delivery: '2-day delivery',
    stock: 145,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    desc: 'Unpasteurised and unfiltered, so it crystallises naturally — that is the sign it has not been processed.',
    features: ['Raw & unfiltered', 'Single source', 'No added sugar', 'Glass jar'],
  },
  {
    id: 40,
    name: 'Mixed Nuts & Dry Fruits — 1kg',
    seller: 'Pantry Staples',
    price: 1399,
    mrp: 2099,
    rating: 4.6,
    reviews: 1820,
    category: 'Grocery',
    tag: 'Flash sale',
    delivery: 'Next-day delivery',
    stock: 122,
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=600&q=80',
    desc: 'Almonds, cashews, pistachios and walnuts, unroasted and unsalted, in a resealable vacuum pack.',
    features: ['4 varieties', 'Unsalted', 'Resealable pack', 'Vacuum sealed'],
  },
]

export const sellers = [
  { name: 'Acme Electronics', rating: 4.8, orders: '124k', since: 2019, focus: 'Audio & computing' },
  { name: 'Glow Lab', rating: 4.9, orders: '312k', since: 2020, focus: 'Skincare & cosmetics' },
  { name: 'ZenFlex', rating: 4.7, orders: '86k', since: 2021, focus: 'Yoga & recovery' },
  { name: 'Brew & Co.', rating: 4.9, orders: '58k', since: 2018, focus: 'Coffee & brewing' },
  { name: 'North Thread', rating: 4.6, orders: '92k', since: 2020, focus: 'Everyday apparel' },
  { name: 'DeskLab Pro', rating: 4.8, orders: '71k', since: 2021, focus: 'Desk ergonomics' },
  { name: 'PureLiving', rating: 4.7, orders: '44k', since: 2022, focus: 'Air & water' },
  { name: 'ProFit Gear', rating: 4.8, orders: '138k', since: 2019, focus: 'Training equipment' },
]

export const trackingStages = [
  { title: 'Order placed', desc: 'Invoice card delivered into your chat with the merchant.', done: true },
  { title: 'Packed', desc: 'Seller confirms and shares a packing photo in the same thread.', done: true },
  { title: 'Shipped', desc: 'Courier assigned. Live location updates arrive as messages.', done: true },
  { title: 'Out for delivery', desc: 'Rider details and a two-hour window land in your chat.', done: false },
  { title: 'Delivered', desc: 'Signed delivery confirmation, plus a one-tap return window.', done: false },
]

export const protectionPoints = [
  {
    title: '7-day easy returns',
    desc: 'Start a return from the order card in your chat. Pickup is scheduled without a phone call.',
  },
  {
    title: 'Money held until delivery',
    desc: 'Payment sits in escrow until the item is marked delivered. Sellers cannot draw it early.',
  },
  {
    title: 'Verified sellers only',
    desc: 'Every merchant clears GST verification, identity checks and a review audit before listing.',
  },
  {
    title: 'Encrypted order chat',
    desc: 'Your conversation with the seller — address included — is end-to-end encrypted like any other chat.',
  },
  {
    title: 'Dispute resolution in 48 hours',
    desc: 'If something goes wrong, a human reviews the thread and decides within two business days.',
  },
  {
    title: 'No dark patterns',
    desc: 'No pre-ticked add-ons, no countdown pressure on the checkout screen, no hidden fees at the last step.',
  },
]

export const marketplaceFeatures = [
  { title: 'Buy inside a conversation', desc: 'Tap a catalogue card and check out without ever leaving the thread.' },
  { title: 'Escrow by default', desc: 'Money is released to the seller only once the order is marked delivered.' },
  { title: 'Verified merchants', desc: 'GST verification, identity checks and a review audit before a store goes live.' },
  { title: 'Live order tracking', desc: 'Every status change arrives as a message, not as an email you will never open.' },
  { title: 'One-tap returns', desc: 'Start a return from the order card. Pickup is scheduled automatically.' },
  { title: 'Encrypted address', desc: 'Your delivery details are shared end-to-end encrypted with the seller alone.' },
  { title: 'Wishlist that syncs', desc: 'Save items across devices and get a nudge only when the price actually drops.' },
  { title: 'Group buying', desc: 'Share a cart into a group so friends can add items and split the total.' },
  { title: 'Honest pricing', desc: 'The price on the card is the price at checkout. Delivery is shown before you commit.' },
]

export const marketplaceSteps = [
  { title: 'Browse the catalogue', desc: 'Search 40+ products or open a store’s catalogue straight from its chat profile.' },
  { title: 'Add to your cart', desc: 'Adjust quantities, apply an offer and see the full total before anything is charged.' },
  { title: 'Pay in one tap', desc: 'Approve with a passkey. Money goes into escrow, not straight to the seller.' },
  { title: 'Track and return', desc: 'Follow the order in chat, and start a return from the same card within seven days.' },
]

export const marketplaceFaqs = [
  {
    q: 'How does buying inside a chat actually work?',
    a: 'Tapping “Buy in chat” opens an encrypted invoice card in your conversation with the merchant. You confirm with a passkey and the receipt stays in the thread as your record.',
    tag: 'Buying',
  },
  {
    q: 'Are the sellers verified?',
    a: 'Yes. Every merchant clears GST verification, an identity check and a review audit before receiving the verified badge. Stores that fall below a rating threshold are re-audited.',
    tag: 'Trust',
  },
  {
    q: 'What is the return policy?',
    a: 'Seven days from delivery on almost everything, with pickup scheduled from the order card. Perishables and personal-care items that have been opened are the usual exceptions.',
    tag: 'Returns',
  },
  {
    q: 'When does the seller get my money?',
    a: 'Only after the order is marked delivered. Until then it sits in escrow, which is what makes disputes resolvable rather than a negotiation.',
    tag: 'Payments',
  },
  {
    q: 'Who can see my delivery address?',
    a: 'Only the seller you are buying from, and only for the duration of the order. The address is shared end-to-end encrypted and is not used for advertising.',
    tag: 'Privacy',
  },
  {
    q: 'Are there hidden charges at checkout?',
    a: 'No. The price on the card is the price you pay. Delivery cost, if any, is shown before you confirm — never added on the final screen.',
    tag: 'Pricing',
  },
  {
    q: 'Can I split a purchase with friends?',
    a: 'Yes. Share the cart into a group chat and each person pays their share through KT Wallet. The order ships once every share is settled.',
    tag: 'Group buying',
  },
  {
    q: 'What if the item arrives damaged?',
    a: 'Report it from the order card with a photo. A human reviews the thread and decides within two business days, and escrow means the refund is straightforward.',
    tag: 'Disputes',
  },
  {
    q: 'How do I sell on KT Marketplace?',
    a: 'Create a business profile, complete GST and identity verification, then upload a catalogue. Most stores are live within 48 hours and there is no listing fee.',
    tag: 'Selling',
  },
  {
    q: 'Do you charge sellers a commission?',
    a: 'A flat 2% on settled orders with no listing fees, no ad auctions and no paid placement. Search ranking cannot be bought.',
    tag: 'Selling',
  },
]

export const marketplaceReviews = [
  {
    quote: 'Ordering from a chat sounded gimmicky until I did it once. Now the whole order history lives in one thread.',
    name: 'Divya Krishnan',
    role: 'Architect, Bengaluru',
  },
  {
    quote: 'Escrow is the feature. I stopped worrying about small sellers the moment I understood how it works.',
    name: 'Thomas Berg',
    role: 'Buyer, Oslo',
  },
  {
    quote: 'Started my bakery catalogue on a Sunday and had orders by Tuesday. No website, no listing fee.',
    name: 'Zoya Khan',
    role: 'Home baker, Lucknow',
  },
  {
    quote: 'The return took two taps and a pickup the next morning. That is the entire review.',
    name: 'Aarav Sethi',
    role: 'Student, Jaipur',
  },
  {
    quote: 'Group cart for our office coffee order saved a spreadsheet and about forty messages.',
    name: 'Laura Mendes',
    role: 'Office manager, São Paulo',
  },
  {
    quote: 'No pre-ticked insurance, no countdown timer, no surprise fee. Checkout is boring in the best way.',
    name: 'Hassan Ali',
    role: 'Buyer, Dubai',
  },
]
